### ISSUE TITLE
Adding support for classes of the same name in different packages!!!

### ISSUE THREAD

**Issue by duckladydinh** [swagger-api/swagger-core#2861] opened 2018-06-29 13:50 UTC
Hello,

Swagger is great and I am learning to use it with Java Implementation. However, when I have too classes of the same name, I do not know how I should handle it because Swagger only supports simple names.
Is there anyway to enable Swagger to generate YAML with full class name (package + simple name)?
Thank you.

**Comment by frantuma** [comment] 2018-07-17 12:18
independently of the version you are referring to (1.x or 2.x), seems to be a duplicate of #2121 and related PRs #2797 and #2798. Check comment in  https://github.com/swagger-api/swagger-core/pull/2691#issuecomment-386611105 with related links, for 2.0 a custom resolved for this scenario is https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/CustomResolverTest.java#L49

**Closed by frantuma** 2018-07-17 12:18 UTC

**Comment by gautelote** [comment] 2021-03-17 21:19
We are running into the same issue - that swagger apparently does not support different versions of classes with the same name in different packages.
Is there any workaround for this problem? 
Or do we need to rename our classes to unique names?

**Comment by ande13** [comment] 2021-04-15 14:14
> We are running into the same issue - that swagger apparently does not support different versions of classes with the same name in different packages.
> Is there any workaround for this problem?
> Or do we need to rename our classes to unique names?

For java, you can use the following workaround

@Primary
@Component
public class SwaggerApiModelTypeNameProvider extends ApiModelTypeNameProvider {

    @Override
    public String nameFor(Class<?> type) {
        ApiModel annotation = AnnotationUtils.findAnnotation(type, ApiModel.class);
        String defaultTypeName = type.getTypeName().replace(type.getPackageName() + ".", "");
        return annotation != null ? Optional.ofNullable(Strings.emptyToNull(annotation.value())).orElse(defaultTypeName) : defaultTypeName;

    }
}

Hope this solve your problem.

**Comment by bestarshad** [comment] 2021-05-30 07:55
please refer the files in repo for the fix

same class name issue fix in open api swagger it will generate schema request response as per java annotation naming convention against the java variables. it will not create schema request response as per java variables it will follow schema annotation

[github](https://github.com/bestarshad/openapiswaggerfix)

**Comment by Poorva17** [comment] 2022-06-19 17:44
Any workaround for kotlin?

**Comment by OctoOsmo** [comment] 2022-12-15 12:03
> Any workaround for kotlin?

<img width="382" alt="Screenshot 2022-12-15 at 13 02 54" src="https://user-images.githubusercontent.com/3993121/207854522-4a20ddc5-8112-4dff-af4f-06cdb8e95026.png">
