### ISSUE TITLE
Response references in Yaml ObjectMapper

### ISSUE THREAD

**Issue by imnotbarney** [swagger-api/swagger-core#1198] opened 2015-06-24 10:51 UTC
Hello,

I have been using the ObjectMapper defined in the 'Yaml' class to convert a swagger defintion file into Java objects. 

I've found an issue with the Response class, as it doesn't seem to support the Response if it is a reference to a response defined on the top level. 

An example of the swagger file I would be wanting to parse is shown below.

    swagger: '2.0'
    info:
      title: REST API
      description: REST API
      version: '1'
    basePath: /api/rest
    paths:
      '/getExample':
        get:
          responses:
            '404':
              $ref: '#/responses/NotFound'
    responses:
      NotFound:
        description: Entity not found
        schema:
          $ref: '#/definitions/Error'
    definitions:
      Error:
        type: string

**Comment by webron** [comment] 2015-06-24 11:05
Right, but you're actually looking for the [swagger-parser] (https://github.com/swagger-api/swagger-parser) project if you want to convert a Java definition to POJOs. Some features may indeed not be supported by it.

**Comment by webron** [comment] 2015-07-14 07:10
Duplicate of #1133.

**Closed by webron** 2015-07-14 07:10 UTC
