### ISSUE TITLE
Disabling MapperFeature.DEFAULT_VIEW_INCLUSION is not respected in ModelResolver#hiddenByJsonView

### ISSUE THREAD

**Issue by denis111** [swagger-api/swagger-core#3464] opened 2020-03-05 12:26 UTC
Here https://github.com/swagger-api/swagger-core/blob/4fe32771edc05aed86ddbac5c856ceade13be8d7/modules/swagger-core/src/main/java/io/swagger/v3/core/jackson/ModelResolver.java#L1983 it should return true if DEFAULT_VIEW_INCLUSION is disabled in ObjectMapper.

**Comment by frantuma** [comment] 2020-03-13 15:13
Thanks for reporting this, not sure about the possible scenarios though; `ObjectMapper` used by `ModelResolver` can (and is by default) not the same as e.g. the one used for JSON (de)serialization of payloads by the JAX-RS implementation, or whatever other use. Also if I am not mistaken the fields not annotated with `JsonView` would be not serialized only when serialization explicitly invoked with a view; the desired behaviour would be therefore probably highly project dependent, please let me know what do you think.

A possible alternative approach since latest `2.1.2-SNAPSHOT` would be to customize behaviour if needed by [extending ModelResolver](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver) and overridding `hiddenByJsonView()`.

**Comment by denis111** [comment] 2020-03-16 10:42
Ok, that's fine for now, I can override this now, thanks! But here's the scenario:
I do this on starting my app:
`Json.mapper().disable(MapperFeature.DEFAULT_VIEW_INCLUSION);`
And then this option is not respected as I reported in this issue.

PS: I use Spring Boot Rest controllers without JAX-RS with this library https://springdoc.github.io/springdoc-openapi-demos/ .

**Comment by frantuma** [comment] 2020-03-16 10:51
What do you mean "option is not respected"?

**Comment by denis111** [comment] 2020-03-17 12:28
@frantuma I call Json.mapper().disable(MapperFeature.DEFAULT_VIEW_INCLUSION); on application startup but in swagger a see properties without JsonView listed in api endpoints responses. That's why i thinks the hiddenByJsonView method should return _mapper.isDisabled(MapperFeature.DEFAULT_VIEW_INCLUSION) instead of just false.

**Comment by frantuma** [comment] 2020-03-17 12:52
I still believe this is highly project dependent and  should be handled as mentioned above instead of behaviour changed in core, see e.g. cases as mentioned above where serialization is invoked without a view or similar scenarios

**Comment by frantuma** [comment] 2020-03-18 10:26
Closing ticket, will reopen if alternative solutions come out of any further discussion

**Closed by frantuma** 2020-03-18 10:26 UTC

**Comment by denis111** [comment] 2020-03-18 10:58
@frantuma Ok. Although I disagree that this is highly project dependent as you say because if I'm not mistaken disabled DEFAULT_VIEW_INCLUSION is default configuration for any Spring Boot project...

**Comment by FlorianCodes** [comment] 2020-10-31 13:40
Hi @frantuma,

I agree with @denis111.

If DEFAULT_VIEW_INCLUSION is set to true, then non-annotated fields are serialized and non-annotated fields are shown in the Swagger UI model. This is fine.

If DEFAULT_VIEW_INCLUSION is set to false, then non-annotated fields are NOT serialized, but non-annotated fields are SHOWN in the Swagger UI model.
In this case, the behavior I would have expected is that Swagger UI mirros the behavior of Jackson, i.e. non-annotated fields are NOT shown in the Swagger UI model.

The default value in SpringBoot for DEFAULT_VIEW_INCLUSION is indeed false, leading to the unexpected behavior explained above by default.

**Comment by denis111** [comment] 2020-11-03 16:41
@FlorianCodes thanks! Maybe we should address this issue to https://github.com/springdoc/springdoc-openapi/ then?...

**Comment by FlorianCodes** [comment] 2020-11-04 09:50
@denis111 I think this is a good idea, since this problem is highly associated to Spring. Do you mind to open an issue and link to this issue?

**Comment by denis111** [comment] 2020-11-05 09:55
@FlorianCodes there's similar issue https://github.com/springdoc/springdoc-openapi/issues/665 (but also closed)

**Comment by alexander793** [comment] 2023-08-21 14:37
Is there a solution to this issue by now?
Just encountered the same problem with springdoc-openapi-starter-webmvc-ui version 2.1.0
