### ISSUE TITLE
Support for Java Record

### ISSUE THREAD

**Issue by christophe-f** [swagger-api/swagger-core#3867] opened 2021-01-27 13:55 UTC
Schemas are not generated when using Java Record

**Comment by durimkryeziu** [comment] 2021-04-28 10:35
Any estimation on this?

**Comment by ddadon10** [comment] 2021-09-15 11:31
Hi, I would love to see Record support for Swagger also, do you have any news on this issue?

**Comment by ddadon10** [comment] 2021-10-03 10:04
Actually I just tested with [Swagger Maven Plugin](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-maven-plugin/README.md) and it worked! Schemas are generated with Java records out of the box :) 

I did not test with the other way of schema generation.

**Comment by lightbody** [comment] 2021-12-14 14:58
We're using Swagger v3 2.1.10 (via Micronaut) and here is what a simple `Foo` class with a `String` `bar` field looks like, without records:


```yaml
    Foo:
      required:
      - bar
      type: object
      properties:
        bar:
          type: string
```

And when I convert it to a record we get this:

```yaml
    Foo:
      allOf:
      - $ref: '#/components/schemas/Record'
      - required:
        - bar
        type: object
        properties:
          bar:
            type: string

...

    Record:
      type: object
```

I'm not fluent enough with OpenAPI syntax to know if the second example is "wrong", but I know it's _different_ and that alone has caused us issues with some of the downstream automation we use to process the definitions and turn them into TypeScript types.

All that said: it's unclear to me if Swagger officially supports records and, if so, if this is a bug or intended behavior. Anyone know? Thanks!

**Comment by micryc** [comment] 2024-10-18 11:42
Suport for Java Records in swagger-core already exists and was checked by series of tests: https://github.com/swagger-api/swagger-core/pull/4749, closing issue, If there will be any concerns, feel free to reopen.

**Closed by micryc** 2024-10-18 11:42 UTC
