### ISSUE TITLE
Swagger support for @JsonView

### ISSUE THREAD

**Issue by prabusb** [swagger-api/swagger-core#2595] opened 2017-12-20 09:22 UTC
Hi,
In my project, I heavily use jsonview to return different response for each endpoint for same resource.

For example - I have an resource called Student. In first end point I may return only 5 attributes and in second endpoint I may return additional 2 attributes.

When I try swagger, it generates the doc for whole object, not for the view.

I tried to google and not getting enough details whether swagger supports jsonview. Can you please let me know how to get it resolved?

**Comment by frantuma** [comment] 2017-12-20 10:22
Hi, atm `JsonView` is not supported in swagger; such support is however considered for future release as it is a quite requested features, as in #479 and #2079 (any PR in this area is welcome).
Closing as duplicate of #479 and #2079

**Closed by frantuma** 2017-12-20 10:22 UTC
