### ISSUE TITLE
Remove "empty" property in generated schema for class extending HashMap

### ISSUE THREAD

**Issue by valentinabojan** [swagger-api/swagger-core#3535] opened 2020-04-27 12:27 UTC
Hello,

I have a class that extends "HashMap". The schema generated for it contains a boolean "empty" property and a string "additionalProperties". 

Is there a way to **not** have the "empty" property generated in the schema for my class? 
Thanks!

```
public class ContainerTypeSchemaTicket2636Test extends AbstractAnnotationTest {

    @Test
    public void testContainerTypeSchemaTicket2636() throws Exception {
        String expectedYaml = "openapi: 3.0.1\n" +
                "paths:\n" +
                "  /path:\n" +
                "    get:\n" +
                "      summary: Op\n" +
                "      description: 'RequestBody contains a Schema class that extends a Map '\n" +
                "      operationId: getWithNoParameters\n" +
                "      requestBody:\n" +
                "        content:\n" +
                "          application/json:\n" +
                "            schema:\n" +
                "              $ref: '#/components/schemas/MyModel'\n" +
                "        required: true\n" +
                "      responses:\n" +
                "        \"200\":\n" +
                "          description: voila!\n" +
                "components:\n" +
                "  schemas:\n" +
                "    MyModel:\n" +
                "      type: object\n" +
                "      properties:\n" +
                "        empty:\n" +
                "          type: boolean\n" +
                "      additionalProperties:\n" +
                "        type: string";
        compareAsYaml(RequestBodyInheritanceModelIssue.class, expectedYaml);
    }

    static class RequestBodyInheritanceModelIssue {
        @Operation(
                summary = "Op",
                description = "RequestBody contains a Schema class that extends a Map ",
                operationId = "getWithNoParameters",
                responses = {
                        @ApiResponse(
                                responseCode = "200",
                                description = "voila!")
                })
        @GET
        @Path("/path")
        public void simpleGet(@RequestBody(required=true,
                content = @Content(mediaType = "application/json", schema = @Schema(implementation = MyModel.class)))
                                      String data) {
        }
    }

    class MyModel extends HashMap<String, String> {

    }
}
```

**Comment by jonseah** [comment] 2020-08-10 17:45
I'm seeing the same issue too. Is there a workaround to this?

**Comment by LinghaoYu** [comment] 2020-10-19 17:53
Seeing the same issue. Any workaround???

**Comment by frantuma** [comment] 2020-10-19 20:06
depending on the needs, a first way to hide the `empty` property is e.g. having `myModel` override `isEmpty()` like 

```java
class MyModel extends HashMap<String, String> {
  @Hidden
  public boolean isEmpty() {
    return super.isEmpty();
  }
}
```

a slightly more complex (and flexible) alternative is [extending converter](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Extensions#extending-core-resolver) to remove the property (in this case) e.g:


```java
public class MapAwareConverter implements ModelConverter {

    @Override
    public Schema resolve(AnnotatedType type, ModelConverterContext context, Iterator<ModelConverter> chain) {
        if (chain.hasNext()) {
            Schema schema = chain.next().resolve(type, context, chain);
            JavaType _type = Json.mapper().constructType(type.getType());
            if (_type != null) {
                Class<?> cls = _type.getRawClass();
                if (HashMap.class.isAssignableFrom(cls)) {
                    if (schema != null && schema.getProperties() != null) {
                        schema.getProperties().remove("empty");
                        if (schema.getProperties().isEmpty()) {
                            schema.setProperties(null);
                        }
                    }
                }
            }
            return schema;
        } else {
            return null;
        }
    }
}
```

and registering it either programmatically via `ModelConverters.getInstance().addConverter(new MapAwareConverter());` or using [configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties) `modelConverterClasses` property like:

```yaml
resourcePackages:
- io.swagger.sample.resource
prettyPrint: true
modelConverterClasses: my.package.MapAwareConverter
...
```

another approach could be configuring the `ObjectMapper` used by swagger adding a mixIn hiding the property, e.g.:

```java
public class MyProcessor implements ObjectMapperProcessor {
    
    @Override
    public void processJsonObjectMapper(ObjectMapper mapper) {
        mapper.addMixIn(HashMap.class, MapMixin.class);
        //or mapper.addMixIn(MyModel.class, MapMixin.class);
    }

    @Override
    public void processYamlObjectMapper(ObjectMapper mapper) {
        // deprecated
    }
}
```

and

```java
public abstract class MapMixin {

    @JsonIgnore
    public abstract boolean isEmpty();
}
```

the `ObjectMapperProcessor` implementation class can be provided in [configuration](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties) `objectMapperProcessorClass` property, passing the qualified class name


Closing ticket, please reopen if you are still experiencing issues or have further questions.

**Closed by frantuma** 2020-10-19 20:06 UTC

**Comment by Yaytay** [comment] 2023-09-28 09:40
Just want to note that for methods returning the guava ImmutableList/Map the only way of the examples given that worked for me was the ModelConverter added programmatically.
The code for the ModelConverter is almost identical to the above (plus SuppressWarnings({"unchecked", "rawtypes"}) and isOpenApi31() returns true).

I can't add annotations to the Immutable classes and the mixins didn't work, and nor did configuring the ModelConverter by class name (it only got called once, for String).

**Comment by HJK181** [comment] 2024-02-22 10:50
@frantuma @Yaytay I'm having a similar issue, and I don't know how to fix it: I have a class QueryDTO which extends Query. Inside Query I have a field `Map<Score, Double> scores` where Score is an enum: `enum Score {FOO, BAR} `. This results in the following api-doc
```
scores:
{
  "type": "object",
  "properties": {
    "empty": {
      "type": "boolean"
    }
  },
  "additionalProperties": {
    "type": "number",
    "format": "double"
  }
}
```
I'm then using ` @rtk-query/codegen-openapi` to create my API, but the generated code doesn't compile because of the following TS error `TS2411: Property empty of type boolean is not assignable to string index type number` QueryDTO:
```
export type QueryDto = {
  query?: string;
  scores?: {
    empty?: boolean;
    [key: string]: number;
  };
```  
I'm pretty new to swagger/openapi and rtk-query codegen, so I'm not sure where the root cause of the issue resists. I would have expected that the api-docs return a definition for my Scores enum wich is used inside the Map's key, but that's not the case.

**Comment by HJK181** [comment] 2024-03-28 11:54
@frantuma @micryc Any help is appreciated.
