### ISSUE TITLE
ApiReponse configuration for file download

### ISSUE THREAD

**Issue by vhochstein** [swagger-api/swagger-core#1876] opened 2016-08-03 06:04 UTC
Hi,

may I configure ApiResponse to receive the following swagger specification:
responses:
200:
description: Returns PDF
schema:
type: file

These two variations do not work:
@ApiResponse(code = 200, message = "Returns PDF")
@ApiResponse(code = 200, message = "Returns PDF", response = File.class)

**Comment by jelaby** [comment] 2016-08-17 17:09
I think that this is a duplicate of #1290. The answer appears to be "no" at the moment.

**Comment by fehguy** [comment] 2016-12-21 00:08
Use `response=byte.class` to properly represent a file download, and set the `@Produces` appropriately.

**Closed by fehguy** 2016-12-21 00:08 UTC
