### ISSUE TITLE
ApiImplicitParam of dataType="file" and paramType="form" leads to an error log

### ISSUE THREAD

**Issue by pjfanning** [swagger-api/swagger-core#1660] opened 2016-02-12 13:57 UTC
I reported https://github.com/swagger-api/swagger-core/issues/1653 but I have another dataType="file" param and this type it is paramType="form".

```java
    new ApiImplicitParam(name = "file", value = "xls[m,x] file", required = true, dataType = "file", paramType = "form")
```
This also leads to the Swagger code reporting:

`` 
[07-Feb-2016 21:11:13.901 GMT] ERROR [io.swagger.util.ReflectionUtils] Failed to resolve 'file' into class java.lang.ClassNotFoundException: file at java.net.URLClassLoader.findClass(URLClassLoader.java:381) at java.lang.ClassLoader.loadClass(ClassLoader.java:424) at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331) at java.lang.ClassLoader.loadClass(ClassLoader.java:357) at java.lang.Class.forName0(Native Method) at java.lang.Class.forName(Class.java:264) at io.swagger.util.ReflectionUtils.typeFromString(ReflectionUtils.java:29) at io.swagger.jaxrs.Reader.readImplicitParam(Reader.java:436) at io.swagger.jaxrs.Reader.readImplicitParameters(Reader.java:412) at io.swagger.jaxrs.Reader.read(Reader.java:399) at io.swagger.jaxrs.Reader.read(Reader.java:147) at com.github.swagger.spray.SwaggerHttpService$class.swagger(SwaggerHttpService.scala:54)
``

**Comment by webron** [comment] 2016-02-12 14:47
This is still a duplicate of #1319 - the solution is there.

**Closed by webron** 2016-02-12 14:47 UTC
