### ISSUE TITLE
Issues with output of XmlElementWrapper

### ISSUE THREAD

**Issue by bill-okara** [swagger-api/swagger-core#2170] opened 2017-04-10 17:47 UTC
Hi,
using swagger 1.5.13, swagger-ui 3, the following jaxb annotations

@XmlElementWrapper(name = "messages)
@XmlElement(name = "message")
public List\<Message\> messages;

will be outputted (with swagger-jersey2-jaxrs) as:

```
"messages": {
    "type": "array",
    "xml": {
        "wrapped": true
    },
    "items": {
        "xml": {
            "name": "message"
        },
       "$ref": "#/definitions/Message"
   }
},
"Message":{
    "type":"object",
    "properties":
    ...
}
```

but in swagger-ui, it's being outputted as:
```
<messages>
    <messages type="error">
        <value>string</value>
    </messages>
</messages>
```

that is, both the child element and the parent wrapper element are having \<messages\> instead of \<messages\>\<message\>

1) is there something wrong with the core spec output? e.g., does the wrapper definition need the "name" in the "xml"? like
```
"messages": {
    "type": "array",
    "xml": {
        "wrapped": true,
       "name" : "messages"       <== Need "name" here?
    },

```
2) or something wrong with the swagger-ui parsing?

Thanks,
Bill

**Comment by webron** [comment] 2017-04-12 07:43
@bill-okara this looks like an issue with swagger-ui. Can you reopen the issue there?

**Comment by bill-okara** [comment] 2017-04-12 16:03
thanks Ron, opened in swagger-ui #2907.

**Comment by webron** [comment] 2017-04-12 16:23
Going to close this one though as the issue is unrelated to core.

**Closed by webron** 2017-04-12 16:23 UTC
