### ISSUE TITLE
Migration guide from 1.5 to 2.x is still unfilled, migration is a pain

### ISSUE THREAD

**Issue by N4zroth** [swagger-api/swagger-core#3382] opened 2019-12-10 09:23 UTC
The page https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Migration-from-1.5 remains untouched and empty for over one and a half years, making migration super painful for users. Will there be a guideline at all?

**Comment by codingchica** [comment] 2019-12-28 04:19
This issue appears to be a duplicate of the yet-unresolved ticket: https://github.com/swagger-api/swagger-core/issues/3059

**Comment by frantuma** [comment] 2020-03-22 17:57
closed as duplicate of #3059

**Closed by frantuma** 2020-03-22 17:57 UTC
