### ISSUE TITLE
@ApiParam mising type parameter

### ISSUE THREAD

**Issue by pbielicki** [swagger-api/swagger-core#846] opened 2015-02-02 09:42 UTC
In my opinion @ApiParam annotation is missing <code>type</code> parameter equivalent of @ApiResponse i.e.:

<code>Class<?> response() default Void.class;</code>

I'm using swagger-jaxrs_2.10-1.3.5 and all the method parameters of type <code>MyResponse&lt;TheResponse&gt;</code> annotated with @ApiParam end up with "type" : "void". More so, SwaggerUI less or equal to 2.0.39 (taken from swagger.js) is basically crashing on line <code>734: if(type.toLowerCase() === 'boolean') { </code> as type is <i>undefined</i>

**Comment by webron** [comment] 2015-02-02 10:38
I'd advise upgrading to 1.3.12 as the behavior you describe is odd and seems like a bug rather than the intended behavior. Parameters should never have the type `void`.

**Comment by pbielicki** [comment] 2015-02-02 13:11
it's a bit better (as the type is not void anymore) but now swagger-ui.js 2.0.23 crashes on line <code>1672: if (type.toLowerCase() === 'file') {</code> and in version 2.1.0-alpha.7 data type is empty:

<img src="http://s18.postimg.org/7bg438m6x/swagger_ui.png" />

If I was able to tell @ApiParam which type I would like to use (like in @ApiResponse) I think it could help.

**Comment by webron** [comment] 2015-02-02 13:12
Can you share the relevant part of the swagger spec that gives you the error/wrong output?

**Comment by pbielicki** [comment] 2015-02-02 13:13
can I paste it here? (it's almost 90 lines)

**Comment by webron** [comment] 2015-02-02 13:14
Sure

**Comment by pbielicki** [comment] 2015-02-02 13:15
{
  "apiVersion": "1.0.0",
  "swaggerVersion": "1.2",
  "basePath": "../../rest-services/v1",
  "resourcePath": "/filterEvents",
  "apis": [{
    "path": "/filterEvents/event",
    "operations": [{
      "method": "POST",
      "summary": "Post a set of EventType on given impacted entities.",
      "notes": "",
      "type": "EventType",
      "nickname": "processEventFliter",
      "produces": ["application/json",
      "application/xml"],
      "consumes": ["application/json",
      "application/xml"],
      "parameters": [{
        "name": "body",
        "description": "Set of EventType and impacted entities.",
        "required": false,
        "items": {
          "$ref": "EventType"
        },
        "paramType": "body",
        "allowMultiple": false
      }]
    }]
  }],
  "models": {
    "EventType": {
      "id": "EventType",
      "required": ["EventProperties"],
      "properties": {
        "EventProperties": {
          "$ref": "EventPropertiesType"
        },
        "ImpactedEntities": {
          "$ref": "ImpactedEntitiesType"
        },
        "setEventProperties": {
          "type": "boolean"
        },
        "setImpactedEntities": {
          "type": "boolean"
        }
      }
    },
    "EventPropertiesType": {
      "id": "EventPropertiesType",
      "required": ["Type"],
      "properties": {
        "Type": {
          "type": "string",
          "enum": ["OPERATION_CLOSURE",
          "DELETE_FLIGHT"]
        },
        "Source": {
          "type": "string"
        },
        "OccurrenceTime": {
          "type": "string",
          "format": "date-time"
        },
        "OccurrenceId": {
          "type": "string"
        },
        "setSource": {
          "type": "boolean"
        },
        "setType": {
          "type": "boolean"
        },
        "setOccurrenceTime": {
          "type": "boolean"
        },
        "setOccurrenceId": {
          "type": "boolean"
        }
      }
    },
    "ImpactedEntitiesType": {
      "id": "ImpactedEntitiesType",
      "properties": {
        "flightLegChangeSetOrAircraftVisitChangeSet": {
          "$ref": "Serializable"
        },
        "setFlightLegChangeSetOrAircraftVisitChangeSet": {
          "type": "boolean"
        }
      }
    }
  }
}

**Comment by webron** [comment] 2015-02-02 13:18
Okay, something is wrong with that output.

Can you share the method signature that produces that (with the annotations)?

**Comment by pbielicki** [comment] 2015-02-02 13:19
@Path("filterEvents")
@Api(value = "/filterEvents", description = "Services dealing with EventType filtering.")
public interface EventFilterResource {

  @POST
  @Path("/event")
  @Produces({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
  @Consumes({ MediaType.APPLICATION_JSON, MediaType.APPLICATION_XML })
  @ApiOperation(value = "Post a set of EventType on given impacted entities.", response = EventType.class)
  public MyResponse<MyResponse<EventType>> processEventFliter(
      @ApiParam(value = "Set of EventType and impacted entities.") @Valid MyEventRequest<EventType> events);

**Comment by webron** [comment] 2015-02-02 13:23
Did you set up a custom deserializer for MyEventRequest?

**Comment by pbielicki** [comment] 2015-02-02 13:24
nope

**Comment by webron** [comment] 2015-02-02 13:26
In that case, that looks like a possible bug with regards to the parsing of the typed class.

**Comment by TuomasKiviaho** [comment] 2015-02-27 11:38
I hope that the proposal for overriding the data type (just by declaring it in string form) could be considered. It's quite cumbersome to register a ``Converter`` compared to ``@XmlSchemaType`` (and ``@XmlJavaTypeAdapter``) of JAXB.  I'd rather declare ``@ApiParam(type="date") LocalDate date`` directly at method level, so that other tools like swagger-doclet can also utilize the annotation.

**Comment by fehguy** [comment] 2015-03-08 17:11
OK I have a couple suggestions.

@TuomasKiviaho can you please open a separate ticket for that enhancement?

@pbielicki The swagger-ui is not on version 2.1.8-M1 and this type check should be fixed.  The cause is downstream in your model, where it's getting the type of `ImpactedEntitiesType` wrong.  If you want to dig into that more, please reopen the issue.

Finally, the 1.5.x code has much better support for introspection as it uses Jackson for parsing.  Please consider upgrading to 1.5.2-M1 or later.

**Closed by fehguy** 2015-03-08 17:11 UTC
