### ISSUE TITLE
Missing array type when using @ArraySchema

### ISSUE THREAD

**Issue by paulrutter** [swagger-api/swagger-core#4641] opened 2024-03-27 15:03 UTC
Since we upgraded from 2.2.11 to 2.2.21, the output when using `@ArraySchema` is no longer correct.
We're outputting 3.1 via `openAPI31: true`.

The output in JSON misses `"type": "array"`.
See example on https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations#arrayschema

Relevant annotations used:
```
content = @Content(
        mediaType = APPLICATION_JSON,
        array = @ArraySchema(schema =  @Schema(implementation = BulkResultBean.class)),
        examples = {
                @ExampleObject(
                    name = "Example bulk response",
                    description = "Example bulk response",
                    value = "description...."
                )
       }
})
```
Left is with 2.2.11, right with 2.2.21.
![image](https://github.com/swagger-api/swagger-core/assets/11535991/0ca12200-23c8-407f-8267-797c8a98a064)

I see several mentions of fixes in array schema in the changelog, but i doubt this output is now correct.

**Comment by micryc** [comment] 2024-05-23 11:08
Hi @paulrutter Are you still experiencing this issue ? I tried to reproduce with core 2.2.22 version and it looks like type shows up in specification. For now I am gonna close this ticket, if issue still appears for you, feel free to reopen

**Comment by paulrutter** [comment] 2024-05-23 14:09
I will check it out @micryc and reopen if needed.

**Comment by taylortails** [comment] 2024-06-06 06:19
I'm seeing this behaviour with 2.2.22 here:
https://github.com/springdoc/springdoc-openapi-demos/issues/68

It's not clear to me yet whether it's a spring or swagger issue

**Comment by taylortails** [comment] 2024-06-06 10:08
This looks to be the cause because a JsonSchema is created without a type:

https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java#L510

**Comment by paulrutter** [comment] 2024-06-06 10:30
@micryc we should reopen, as it apperantly is not fixed (in all cases at least)

**Comment by owen4gh** [comment] 2024-06-17 10:58
Changing line 510 in modles/swagger-core/src/main/java/io/swagger/v3/core/util/AnnotationsUtils.java from

`arraySchemaObject = new JsonSchema();`

to

`arraySchemaObject = new ArraySchema();`

appears to fix the issue.

**Comment by paulrutter** [comment] 2024-06-17 14:45
Can you create a pr for it @owen4gh?

**Comment by owen4gh** [comment] 2024-06-17 15:21
Created https://github.com/swagger-api/swagger-core/pull/4700

**Comment by micryc** [comment] 2024-06-24 13:03
@owen4gh @paulrutter Thank you a lot for reporting this bug and provided fixes, changes merged and I am closing the issue.

**Closed by micryc** 2024-06-24 13:03 UTC

**Comment by paulrutter** [comment] 2024-08-28 07:48
@micryc When will this be part of a release?

**Comment by micryc** [comment] 2024-08-29 11:03
Hi @paulrutter this fix is a part of the newest Core 2.2.23 release

**Comment by paulrutter** [comment] 2024-08-29 11:16
@micryc i don't see it on https://mvnrepository.com/artifact/io.swagger.core.v3/swagger-core yet, is it behind?

**Comment by micryc** [comment] 2024-08-29 11:18
@paulrutter Maven repository is usually delayed, check it here: https://central.sonatype.com/artifact/io.swagger.core.v3/swagger-core
