### ISSUE TITLE
Swagger output is not correct in 1.5.0-M1

### ISSUE THREAD

**Issue by kongchen** [swagger-api/swagger-core#861] opened 2015-02-08 13:53 UTC
It was OK in 1.5.0-SNAPSHOT some days ago, I just upgrade to M1 and some of my unit tests fails, I did not have much time to figure out what's wrong but I found the root cause is the `items` in `schema` of `parameters`:
![image](https://cloud.githubusercontent.com/assets/1485800/6096715/59685c56-afdc-11e4-8693-475a9e9f0bb4.png)
and I found the same issue in http://petstore.swagger.io/#!/user/createUsersWithListInput: 
![image](https://cloud.githubusercontent.com/assets/1485800/6096680/89344082-afda-11e4-817b-05796d9ea626.png)

A bug?

**Comment by fehguy** [comment] 2015-02-08 16:05
Thanks--looks like a bug to me.  Will look into it.

**Comment by fehguy** [comment] 2015-02-09 05:43
OK yep, this was a regression and is addressed in 1.5.1-SNAPSHOT.  Can you please give it a whirl?  Tests have been added.

**Closed** 2015-02-09 05:43 UTC
Labels: Bug
