### ISSUE TITLE
ModelConverters can only be added before others, not after them

### ISSUE THREAD

**Issue by Treppenhouse** [swagger-api/swagger-core#2854] opened 2018-06-22 11:53 UTC
The way to add a new `ModelConverter` is by using `ModelConverters.getInstance().addConverter(myModelConverter)` which adds the new converter _at the front_ of the converters list. This is due to the method being implemented as: `converters.add(0, converter);` 

That means, during the processing phase all existing converters will run afterwards.

In my use case I would like to add the custom converter to the END of the list, using the results that the other converters have already produced. With the current implementation this is unfortunately not possible as the `ModelConverters` class encapsulates all access to the underlying list (and rightfully so). 

Still it would be great to have at least one other method that allows adding my custom converter at the end of the converters list.

I can also provide a pull request if required.

**Comment by frantuma** [comment] 2018-07-03 14:18
Converters are added at the front as by design the converter implementation is responsible for calling or not calling the next converter in the chain. The default converter (`ModelResolver`) is not calling the next converter and therefore any converter after it would not be called.
To achieve your goal (using the results of the other converters), you can call the next converter and then do whatever with the result; this [test converter](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/java/io/swagger/v3/core/converting/override/SnakeCaseConverterTest.java#L77) implements such a scenario.

Closing ticket, please feel free to reopen if you're still experiencing issues or have questions.

**Closed by frantuma** 2018-07-03 14:18 UTC
