### ISSUE TITLE
Question: Will there be OpenAPI 3.1.0 support?

### ISSUE THREAD

**Issue by Numichi** [swagger-api/swagger-core#4058] opened 2021-12-02 12:56 UTC

**Comment by frantuma** [comment] 2021-12-03 01:13
Duplicate of https://github.com/swagger-api/swagger-core/issues/3913

please see https://github.com/swagger-api/swagger-parser/issues/1535#issuecomment-936707841

**Closed by frantuma** 2021-12-03 01:13 UTC
