### ISSUE TITLE
Default value for collectionFormat field is csv. Should be multi.

### ISSUE THREAD

**Issue by pedrombl** [swagger-api/swagger-core#1160] opened 2015-06-11 22:31 UTC
Currently the default value in the field `collectionFormat` is `csv`. However the default way of passing a list of parameters is `multi` (`foo=bar&foo=baz`). Talking with *ron*, *who_* and *jeremyw* in #swagger/freenode this was identified as a bug. 

Here is the part of the code that does that -> https://github.com/swagger-api/swagger-core/blob/9c67549cc4e30db916dac0165f0549485a6eb4c7/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/ParameterProcessor.java#L97

**Comment by webron** [comment] 2015-06-17 05:43
For the sake of documentation, the format is `csv` because of the intent in 1.3.X and we tried to keep it backwards compatible. However, since it really doesn't make sense and breaks the API documentation then it definitely needs to be `multi`. I believe this makes `allowMultiple` obsolete, but for now it should probably also give a `multi` value.

**Comment by ipeluffo** [comment] 2015-06-17 20:04
Hi everyone, I have a similar question about the `collectionFormat`.
Is there any way to set this value for a parameter?

If setting this value is not possible I can create a issue for this.

Thanks in advance

**Comment by webron** [comment] 2015-07-14 15:09
Fixed in develop_2.0.

**Closed by webron** 2015-07-14 15:09 UTC
Labels: Bug, P1

**Comment by Armanda888** [comment] 2016-07-21 18:41
Can I set collectionFormat to be csv for query parameter? as my rest api is like foo=bar, baz

**Comment by fehguy** [comment] 2016-07-21 18:42
yes you can

**Comment by Armanda888** [comment] 2016-07-21 18:58
@fehguy how do I set it? in the annotation ApiParam?

**Comment by Armanda888** [comment] 2016-07-21 19:26
by checking https://github.com/kongchen/swagger-maven-plugin/blob/master/src/main/java/com/github/kongchen/swagger/docgen/reader/AbstractReader.java, Line 417, it sets collectionFormat to multi for query param. 
Here is my query parameter:
ApiParam(name = "include", allowableValues = "a, b", allowMultiple = true, required = false)
@QueryParam("include") String include,
in the swagger.json, it's like this:
{
"name" : "include",
"in" : "query",
"required" : false,
"type" : "array",
"items" : {
"type" : "string",
"default" : "csv",
"enum" : [ "a", "b" ]
},
"collectionFormat" : "multi"
}

**Comment by gkozyryatskyy** [comment] 2017-02-08 14:58
@Armanda888 do you solve your question? have the same problem after update.
There is a support of collectionFormat now available in annotations https://github.com/swagger-api/swagger-core/issues/1180, but seems swagger plugin do not use it.

**Comment by gkozyryatskyy** [comment] 2017-02-08 14:59
@fehguy can you please show how we can set collectionFormat to csv through annotations + swagger plugin?

**Comment by fehguy** [comment] 2017-02-08 15:45
@gkozyryatskyy what swagger plugin are you referring to?  If this is springfox, then it's a separate project that may not support the latest annotations.

**Comment by gkozyryatskyy** [comment] 2017-02-08 16:24
@fehguy this one https://github.com/kongchen/swagger-maven-plugin
seems like the problem is somewhere here https://github.com/kongchen/swagger-maven-plugin/blob/master/src/main/java/com/github/kongchen/swagger/docgen/reader/AbstractReader.java#L441

**Comment by fehguy** [comment] 2017-02-08 16:30
OK looks like we need to open a ticket in that project.

**Comment by gkozyryatskyy** [comment] 2017-02-08 16:51
@fehguy 
done https://github.com/kongchen/swagger-maven-plugin/issues/425

**Comment by apiwoni** [comment] 2019-09-19 21:20
@gkozyryatskyy @fehguy This issue has nothing to do with swagger-maven-plugin but more with ParameterProcessor in swagger-core 1.5.x. Currently setting collectionFormat to csv via annotation is ignored when producing swagger json spec because io.swagger.models.parameters.AbstractSerializableParameter#setType resets collectionFormat to null after it has been set to "csv" anytime type is not array.
