### ISSUE TITLE
OpenAPI deserialization  issue

### ISSUE THREAD

**Issue by DmitriPunko** [swagger-api/swagger-core#3503] opened 2020-04-08 10:44 UTC
When I'm trying to deserialize OpenAPI object from the following yaml:
```
openapi: "3.0.1"
components:
  schemas:
    suppl:
      required:
      - "orderNumber"
      type: "object"
      properties:
        extension:
          type: "object"
          additionalProperties:
            type: "string"
        orderNumber:
          minimum: 1
          type: "number"
          description: "The number"
```

I'm getting next error:
Caused by: **java.lang.IllegalArgumentException: additionalProperties must be either a Boolean or a Schema instance**
	at io.swagger.v3.oas.models.media.Schema.setAdditionalProperties(Schema.java:552)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:139)

Can you help me to know what is wrong in yaml or is there smth wrong in deserialization process? extension - map(string to string), followed your API: https://swagger.io/docs/specification/data-models/dictionaries/

I deserialize using Object Mapper from com.fasterxml.jackson.dataformat:jackson-dataformat-yaml library. Object mapper settings:
`
ObjectMapper objectMapper =
                new ObjectMapper(new YAMLFactory().disable(YAMLGenerator.Feature.WRITE_DOC_START_MARKER));
        objectMapper.enable(JsonParser.Feature.ALLOW_UNQUOTED_CONTROL_CHARS);
        objectMapper.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
        objectMapper.enable(DeserializationFeature.READ_UNKNOWN_ENUM_VALUES_AS_NULL);
`

**Comment by frantuma** [comment] 2020-04-08 10:56
This seems not to be reproducible with the provided mapper `Yaml.mapper()`, please use it (you can customize further if you need it for some reason) instead.

Closing ticket, please reopen if you're still experiencing issues

**Closed by frantuma** 2020-04-08 10:56 UTC

**Comment by DmitriPunko** [comment] 2020-04-08 12:07
Still reproducible with Yaml.mapper() from io.swagger.v3.core.util.Yaml library(2.1.1 version)

**Comment by frantuma** [comment] 2020-04-08 12:22
I still cannot reproduce, the following code works fine with 2.1.1 version

```java
        String spec = "openapi: \"3.0.1\"\n" +
                "components:\n" +
                "  schemas:\n" +
                "    suppl:\n" +
                "      required:\n" +
                "      - \"orderNumber\"\n" +
                "      type: \"object\"\n" +
                "      properties:\n" +
                "        extension:\n" +
                "          type: \"object\"\n" +
                "          additionalProperties:\n" +
                "            type: \"string\"\n" +
                "        orderNumber:\n" +
                "          minimum: 1\n" +
                "          type: \"number\"\n" +
                "          description: \"The number\"";

        OpenAPI openAPI = Yaml.mapper().readValue(spec, OpenAPI.class);
        Yaml.prettyPrint(openAPI);
```

**Comment by DmitriPunko** [comment] 2020-04-08 12:39
Thanks, this is working for me!
