### ISSUE TITLE
NPE in swagger-maven-plugin since version 2.1.2

### ISSUE THREAD

**Issue by BRUTTUZ** [swagger-api/swagger-core#3583] opened 2020-06-05 10:17 UTC
Hi,

i tried to upgrade from 2.1.1 to 2.1.2, but when I do, I get a NPE while generating the openapi schema. 

Configuration:
[configuration.txt](https://github.com/swagger-api/swagger-core/files/4735350/configuration.txt)

Buildlog:
[buildlog.txt](https://github.com/swagger-api/swagger-core/files/4735355/buildlog.txt)

Class where the error occurs (at least I think it's the one)
[class.txt](https://github.com/swagger-api/swagger-core/files/4735357/class.txt)

do you need any more information? Am I doing something wrong? 

Have a nice day!
Christopher

**Comment by frantuma** [comment] 2020-06-05 10:37
can you please share the full class set (bltype, basicdto, etc)?

**Comment by BRUTTUZ** [comment] 2020-06-05 10:45
Sure, sorry for missing tis out. It's nothing special though:

BLType:
`
public enum BLType {
    MASTER, HOUSE
}
`

AddressType:
`
public enum AddressQualifier {
    A1, A2, A3, A4, A5, A6, A7, A8, A9, AGT, CAR, CNE, CUS, DEL, DEP, DL1, DL2, INV, MIS, NFY, PUP, SHP, TRA
}
`

BasicDTO:
`
package de.cargosoft.api.commons.dto.basicdata;

public interface BasicDTO {

}
`

**Comment by frantuma** [comment] 2020-06-05 11:07
thanks, still missing the resource referring to this pojos

**Comment by BRUTTUZ** [comment] 2020-06-05 11:16
Interface where the schema is generated from:
```
package de.cargosoft.api.commons.restclient.shipment.address;

import de.cargosoft.api.commons.dto.basicdata.address.qualifier.AddressQualifier;
import de.cargosoft.api.commons.dto.shipment.BLType;
import de.cargosoft.api.commons.dto.shipment.address.ShipmentAddress;
import de.cargosoft.api.commons.restclient.service.crud.CRUDService;
import io.swagger.v3.oas.annotations.Hidden;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.tags.Tags;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.util.Map;

@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@Tags(@Tag(name = "Shipment Address"))
@Path("cargosoft/shipment/{shipmentId}/address")
public interface ShipmentAddressServiceClient extends CRUDService<AddressQualifier, ShipmentAddress> {

    @PathParam("shipmentId")
    Integer shipmentId = null;

    @QueryParam("bl_type")
    BLType blType = null;

    @Override
    @ApiResponse(responseCode = OK_200, description = RECORD_RETRIEVED, content = @Content(mediaType = MediaType.APPLICATION_JSON, array = @ArraySchema(schema = @Schema(implementation = ShipmentAddress[].class))))
    @GET
    Response retrieveAll(@DefaultValue("0") @QueryParam("pageNo") Integer pageNo, @DefaultValue("50") @QueryParam("pageSize") Integer pageSize);

    @Override
    @ApiResponse(responseCode = OK_200, description = RECORD_RETRIEVED, content = @Content(mediaType = MediaType.APPLICATION_JSON, array = @ArraySchema(schema = @Schema(implementation = ShipmentAddress[].class))))
    @GET
    @Path("{id}")
    Response retrieveById(@PathParam("id") AddressQualifier id);

    @Hidden
    @Override
    @POST
    default Response create(ShipmentAddress dto) {
        return NOT_IMPLEMENTED;
    }

    @Hidden
    @Override
    default Response update(AddressQualifier id, Map<String, Object> dtoMap) {
        return NOT_IMPLEMENTED;
    }

    @Hidden
    @Override
    default Response delete(@PathParam("id") AddressQualifier id) {
        return NOT_IMPLEMENTED;
    }
}
```


CRUDService
``` 
package de.cargosoft.api.commons.restclient.service.crud;

import de.cargosoft.api.commons.dto.APIErrorResponse;
import de.cargosoft.api.commons.dto.basicdata.BasicDTO;
import de.cargosoft.api.commons.enums.ApiErrorCode;
import de.cargosoft.api.commons.restclient.service.ProtectedRestServiceClient;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;

import javax.ws.rs.*;
import javax.ws.rs.core.MediaType;
import javax.ws.rs.core.Response;
import java.util.List;
import java.util.Map;

@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
public interface CRUDService<IDType, DTO extends BasicDTO> extends ProtectedRestServiceClient {

    String OK_200 = "200";
    String RECORD_CREATED = "Record created";
    String RECORD_RETRIEVED = "Record retrieved";
    String RECORD_UPDATED = "Record updated";
    String RECORD_DELETED = "Record deleted";
    String RECORDS_RETRIEVED = "Records retrieved";
    String RECORDS_FOUND = "Records found";
    Response NOT_IMPLEMENTED = Response.serverError().entity(new APIErrorResponse(ApiErrorCode.NOT_IMPLEMENTED_YET, "The resource you are calling has not been implemented yet")).build();
    String ID_PATH = "{id}";
    String ID_PARAM = "id";
    String BULK_PATH = "bulk";

    @Operation(summary = "Create record",
            description = "Create a new record",
            responses = {
                    @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = APIErrorResponse.class))),
            })
    @POST
    default Response create(@Parameter(name = "Model", description = "Model of the record you want to create") DTO dto) {
        return NOT_IMPLEMENTED;
    }

    @Operation(summary = "Create multiple records",
            description = "Create multiple new records",
            responses = {
                    @ApiResponse(responseCode = "200", description = RECORD_CREATED),
                    @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = APIErrorResponse.class))),
            })
    @Path(BULK_PATH)
    @POST
    default Response createBulk(List<DTO> dtoList) {
        return NOT_IMPLEMENTED;
    }

    @Operation(summary = "Retrieve all records",
            description = "Scroll through all existing records. ",
            responses = {
                    @ApiResponse(responseCode = "204", description = "No record found", content = @Content(mediaType = MediaType.APPLICATION_JSON)),
                    @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = APIErrorResponse.class))),
            })
    @GET
    default Response retrieveAll(@DefaultValue("0") @QueryParam("pageNo") Integer pageNo, @DefaultValue("50") @QueryParam("pageSize") Integer pageSize) {
        return NOT_IMPLEMENTED;
    }

    @Operation(summary = "Retrieve record",
            description = "Find a existing record by it's database id",
            responses = {
                    @ApiResponse(responseCode = "204", description = "No record found", content = @Content(mediaType = MediaType.APPLICATION_JSON)),
                    @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = APIErrorResponse.class))),
            })
    @GET
    @Path(ID_PATH)
    default Response retrieveById(@Parameter(name = "Database id", description = "Database id of the record you want to retrieve") @PathParam(ID_PARAM) IDType id) {
        return NOT_IMPLEMENTED;
    }

    @Operation(summary = "Update record",
            description = "Update a existing record by it's database id",
            responses = {
                    @ApiResponse(responseCode = "204", description = "No record found", content = @Content(mediaType = MediaType.APPLICATION_JSON)),
                    @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = APIErrorResponse.class))),
            })
    @PUT
    @Path(ID_PATH)
    default Response update(@Parameter(name = "Database id", description = "Database id of the record you want to update.") @PathParam(ID_PARAM) IDType id, Map<String, Object> dtoMap) {
        return NOT_IMPLEMENTED;
    }

    @Operation(summary = "Delete record",
            description = "Delete a record by it's database id",
            responses = {
                    @ApiResponse(responseCode = "204", description = "No record found", content = @Content(mediaType = MediaType.APPLICATION_JSON)),
                    @ApiResponse(responseCode = "500", description = "Internal server error", content = @Content(mediaType = MediaType.APPLICATION_JSON, schema = @Schema(implementation = APIErrorResponse.class))),
            })
    @DELETE
    @Path(ID_PATH)
    default Response delete(@Parameter(name = "Database id", description = "Database id of the record you want to remove") @PathParam(ID_PARAM) IDType id) {
        return NOT_IMPLEMENTED;
    }

}

```

ProtectedRestServiceClient:
```
package de.cargosoft.api.commons.restclient.service;

import io.swagger.v3.oas.annotations.enums.SecuritySchemeIn;
import io.swagger.v3.oas.annotations.enums.SecuritySchemeType;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.security.SecurityScheme;

import javax.ws.rs.Consumes;
import javax.ws.rs.Produces;
import javax.ws.rs.core.MediaType;

import static de.cargosoft.api.commons.restclient.service.ProtectedRestServiceClient.*;

@Produces(MediaType.APPLICATION_JSON)
@Consumes(MediaType.APPLICATION_JSON)
@SecurityScheme(name = JAVA_WEB_TOKEN, type = SecuritySchemeType.HTTP, in = SecuritySchemeIn.HEADER, scheme = BEARER, bearerFormat = JWT)
@SecurityRequirement(name = JAVA_WEB_TOKEN)
public interface ProtectedRestServiceClient {
    String JAVA_WEB_TOKEN = "Java Web Token";
    String JWT = "JWT";
    String BEARER = "bearer";
}
```

**Comment by frantuma** [comment] 2020-06-12 11:50
The root cause of this seems to be providing an array of `ShipmentAddress` to `@ArraySchema(schema = @Schema(implementation = ShipmentAddress[].class)` in :

```
@Override
    @ApiResponse(responseCode = OK_200, description = RECORD_RETRIEVED, content = @Content(mediaType = MediaType.APPLICATION_JSON, array = @ArraySchema(schema = @Schema(implementation = ShipmentAddress[].class))))
    @GET
    Response retrieveAll(@DefaultValue("0") @QueryParam("pageNo") Integer pageNo, @DefaultValue("50") @QueryParam("pageSize") Integer pageSize);

    @Override
    @ApiResponse(responseCode = OK_200, description = RECORD_RETRIEVED, content = @Content(mediaType = MediaType.APPLICATION_JSON, array = @ArraySchema(schema = @Schema(implementation = ShipmentAddress[].class))))
    @GET
    @Path("{id}")
    Response retrieveById(@PathParam("id") AddressQualifier id);
```

instead of `@ArraySchema(schema = @Schema(implementation = ShipmentAddress.class)`

The `@ArraySchema` annotation takes care of defining the schema as an array, while `implementation` holds the class to be resolved into the schema for the array `items`.

Please change the annotation to `@ArraySchema(schema = @Schema(implementation = ShipmentAddress.class)` to fix the issue.

It is true that in `2.1.1` NPE was not raised, but still it resolved into an:

```
type: array
items:
 type: string
```
Which is not the expected behaviour.

As NPEs are bad, #3589 fixes the NPE by resolving such cases (an array defined in `implementation`, which again is not correct) to an array of strings.

Closing ticket, please reopen if you have further questions or issues

```

**Closed by frantuma** 2020-06-12 11:50 UTC
