### ISSUE TITLE
JAXB Annotations Ignored (Default ObjectMapper behavior) for Definitions

### ISSUE THREAD

**Issue by TomDataworks** [swagger-api/swagger-core#960] opened 2015-04-02 19:45 UTC
To replicate this issue, use a data model similar to this one:

https://gist.github.com/TomDataworks/56e2b6e259fd1b971aa8

The XmlAccessType.NONE configuration requires explicit declaration of all JAXB Elements, and behaves as expected when using a JacksonJaxbJsonProvider in Apache CXF. However, when exposing the API listing via Swagger, the definitions match exactly what the JacksonJsonProvider or a standard ObjectMapper would produce.

The element marked @XmlElement(name="body") does not appear in the definition of Message. While @XmlAccessorType(XmlAccessType.NONE) is specified, any elements that are explicitly defined should appear.

There are a number of ObjectMappers in the Swagger codebase, and I am trying to track down which one is responsible for this particular task (generating the definitions).

**Comment by Arven** [comment] 2015-04-02 21:02
Here's a bit of an update, which appears to solve the issue at least for me. I used the singleton class ModelConverters to add a new ModelResolver.

```java
    @Bean
    public ObjectMapper objectMapper() {
        ObjectMapper obMap = new ObjectMapper();
        obMap.setAnnotationIntrospector(new JaxbAnnotationIntrospector(obMap.getTypeFactory()));
        ModelConverters.getInstance().addConverter(new com.wordnik.swagger.jackson.ModelResolver(obMap));
        return obMap;
    }
```

Upon adding this converter, the examples in Swagger-UI as well as the definitions in the swagger.json schema match what is accepted by the JAX-RS service.

**Comment by webron** [comment] 2015-05-09 13:29
It seems like we overwrote the JAXB annotation parsing of Jackson.

For now, the simple solution would be to add both `Json.mapper().registerModule(new JaxbAnnotationModule());` and `Yaml.mapper().registerModule(new JaxbAnnotationModule());` and it should solve the related issues.

**Comment by cwstenberg** [comment] 2015-05-11 08:55
Hi 
trying to get Swagger to reflect JAXB annotations in json model both still unsucessfull trying your suggestions above. I am on release 2.0.0.

@webron When or how should I add or do the new module registrations?

Is there a test for JAXB Annotations in the source?

**Comment by webron** [comment] 2015-05-11 08:57
I assume you mean JAXB 2.0?

You can put it anywhere that loads on start up in your application. If you use BeanConfig, you can set it up at the same place. If you use the Application subclass to register your resources, you can set it there.

**Comment by Poohie** [comment] 2015-05-11 14:35
Hi webron -

Sorry if this is a newbie question, but can you give an example of how to add the json mapper mentioned above (Json.mapper().registerModule(new JaxbAnnotationModule()); and Yaml.mapper().registerModule(new JaxbAnnotationModule())) via BeanConfig?

**Comment by webron** [comment] 2015-05-11 14:43
@Poohie - you don't do that via BeanConfig. You can just add those two lines wherever you initialize the BeanConfig (simply copy and paste as-is, you'd need to add the proper imports as well).

**Comment by Poohie** [comment] 2015-05-11 15:13
@webron:  Again, sorry for my lack of knowledge here.  I really do appreciate the pointers & invaluable information!

I believe if I had used a servlet to initialize the BeanConfig, then simply adding the lines and importing appropriate packages for the json mapper would do the trick.  However, I 1) initialized using Swagger's servlet in web.xml and 2) used Spring's Bean declaration to configure Swagger (see snippets below) and not sure how to add the json mapper.  

Perhaps the simplest thing is to just convert over to using a servlet?

1) Initialize w/Swagger servlet:
    <servlet>
        <servlet-name>Jersey2Config</servlet-name>
        <servlet-class>com.wordnik.swagger.jaxrs.config.DefaultJaxrsConfig</servlet-class>
        <init-param>
            <param-name>api.version</param-name>
            <param-value>1.0.0</param-value>
        </init-param>
        <init-param>
            <param-name>swagger.api.basepath</param-name>
            <param-value>http://localhost:8080/api</param-value>
        </init-param>
        <load-on-startup>2</load-on-startup>
    </servlet>

2) Spring Bean declaration
    <bean id="apiListingResource" class="com.wordnik.swagger.jaxrs.listing.ApiListingResource"/>
    <bean id="swaggerSerializers" class="com.wordnik.swagger.jaxrs.listing.SwaggerSerializers" scope="singleton"/>    
 <bean id="beanConfig" class="com.wordnik.swagger.jaxrs.config.BeanConfig">
        <property name="title" value="Swagger Sample App"/>
        <property name="version" value="1.0.0" />
        <property name="schemes" value="http" />
        <property name="host" value="localhost:8002" />
        <property name="basePath" value="/api"/>
        <property name="resourcePackage" value="io.swagger.resources"/>
        <property name="scan" value="true"/>
    </bean>

**Comment by webron** [comment] 2015-05-11 16:21
Aha! Yes, if you use Spring to configure the BeanConfig, then you can't easily use that.

Those two lines can be added anywhere in your own code (that is, not configuration) that runs as part of your application start up. If you don't have any, then you'd have to create something like it. 

And since you shared your configuration, I may add that you don't need both the servlet `DefaultJaxrsConfig` *and* the `BeanConfig` configuration together, they pretty much override each other. 

You can also take a look at the Bootstrap servlet we have in our samples (https://github.com/swagger-api/swagger-core/blob/master/samples/java-jaxrs/src/main/java/com/wordnik/swagger/sample/Bootstrap.java) - that's used to initialize Swagger with more information, and that's also a place where you can put those two extra lines of code.

**Comment by Poohie** [comment] 2015-05-11 17:48
@webron: Eureka!  Very grateful for your guidance and expertise on helping resolve this!

In summary: Changed from using Spring bean config with Jersey to use Bootstrap servlet to initialize and configure Swagger in order to add the extra lines of code required for Swagger to recognize the JAXB annotations (which aren't automatically picked up with swagger core 1.5).

**Comment by webron** [comment] 2015-05-11 18:40
@Poohie - thanks for the update and confirmation it works.

**Comment by fehguy** [comment] 2015-05-20 05:18
@webron @Poohie can we close this?

**Comment by webron** [comment] 2015-05-20 12:53
@fehguy - Depends. Do we want to support JAXB annotations by default? If so, I'll fix it in the code. If not, I'll document how to add support for it.

**Comment by webron** [comment] 2015-06-05 21:12
Okay, after some additional research, we never provided full support for JAXB annotations but rather a subset of those. I believe the same subset is supported now as well.

There is a way to add full scanning as mentioned above, but we're not going to add it to the code for now. We'll add documentation for the process so that it would at least be easier for the users.

**Comment by CSchulz** [comment] 2015-06-23 12:09
Any update on this? At least some documentation update?

**Comment by webron** [comment] 2015-06-23 12:10
The documentation wasn't updated yet, but the solution is in the thread, just read it through.

**Comment by CSchulz** [comment] 2015-06-23 13:15
Using Resteasy of WildFly 8.2.0 with a Servlet including an own BeanConfig. Added the above mentioned module (JaxbAnnotationModule) to my JSON mapper, but no fields are exposed via swagger.json.

```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(namespace = "http://namespace/v1")
@AssociationOverride(...)
public class FloatPackage extends AbstractItem {

    @NotNull
    @AttributeOverride(name = "value", column = @Column(name = "FGP_NUMBER", unique = true))
    private PackageNumber packageNumber;
```

Did I miss anything?

**Comment by webron** [comment] 2015-06-23 13:16
Follow https://github.com/swagger-api/swagger-core/issues/960#issuecomment-100484695 and onwards please.

**Comment by CSchulz** [comment] 2015-06-23 13:31
I am sorry, but I have read it multiple times without success. I think I still miss some small detail.
My servlet looks like the following including the registerModule from the linked comment.

```
public class SwaggerServlet extends HttpServlet {
    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);

        Json.mapper().registerModule(new JaxbAnnotationModule());
        Yaml.mapper().registerModule(new JaxbAnnotationModule());

        BeanConfig beanConfig = new BeanConfig();
```

**Comment by webron** [comment] 2015-06-23 13:36
What fields do you find to be missing in the output? Need some explicit examples of what you have and what you expect to see.

**Comment by CSchulz** [comment] 2015-06-23 13:50
For example the XmlJavaTypeAdapter annotation is ignored:

```
@XmlAccessorType(XmlAccessType.FIELD)
@XmlRootElement(namespace = "http://namespace/v1")
@AssociationOverride(...)
public class FloatPackage extends AbstractItem {

    @NotNull
    @AttributeOverride(name = "value", column = @Column(name = "FGP_NUMBER", unique = true))
    private PackageNumber packageNumber;
```

The class PackageNumber:
```
@Embeddable
@XmlJavaTypeAdapter(PackageNumber.Adapter.class)
public class PackageNumber extends AbstractValueObject<String> {
```

AbstractValueObject:
```
@MappedSuperclass
public abstract class AbstractValueObject<V> {
    @Expose
    private V value;
```

XSD output:
```
  <xs:complexType name="Package">
    <xs:complexContent>
      <xs:extension base="abstractStockItem">
        <xs:sequence>
          <xs:element minOccurs="0" name="PackageNumber" type="xs:string"/>
```

swagger.json output:
```
    "PackageNumber" : {
      "type" : "object",
      "properties" : {
        "value" : {
          "type" : "string"
        }
      }
    },
```

I expect that PackageNumber gets a string in swagger.json like in the xsd.

**Comment by webron** [comment] 2015-06-23 15:00
This may actually be a problem with Jackson. First thing to try is to upgrade the Jackson dependencies to the latest, which I think is 2.5.4 and try (need to make sure the new version overrides the existing ones for all relevant dependencies). 

If that doesn't work, we'd need some simple test case that reproduces the problem which we can use for further debugging.

**Comment by CSchulz** [comment] 2015-06-24 12:39
I have tried 2.5.4 and 2.6.0-RC2 without any success. I will prepare a simple test case based on the about provided classes.

**Comment by webron** [comment] 2015-06-24 12:45
Before that, let's run a little test.

Can you add something like `@XmlTransient` on any of the fields? (I assume you don't use Jackson annotations at all). To be on the safe side and completely clobber it, you can put it on the field declaration, setter *and* getter just to be on the safe side. Then run it and see if that field disappears from the documentation.

If the property disappears, then the issue is not with the integration with Jackson but rather the Jackson parsing itself.

**Comment by CSchulz** [comment] 2015-06-24 12:55
`@XmlTransient` was working after adding the JaxbAnnotationMappingModule. There was no need for `@ApiModelProperty` to overwrite some fields anymore, because you can hide them.

**Comment by webron** [comment] 2015-06-24 12:56
And before JaxbAnnotationMappingModule, `@XmlTransient` was ignore, correct?

**Comment by CSchulz** [comment] 2015-06-24 12:58
Yes correct. Before I used `@ApiModelProperty` to hide information with overwritting data types.

**Comment by webron** [comment] 2015-06-24 13:19
Yeah, so as I was afraid, this is an issue with the JaxbAnnotationMappingModule Jackson component and not really within our control. I can open an issue with Jackson about it, but a simple project that reproduces it may help with further debugging there. Can't make any promises regarding to when/if this will be fixed.

For now, I believe you can overcome it by writing your own model converters, but that would indeed require extra coding from your end.

**Comment by CSchulz** [comment] 2015-06-24 13:50
Open an issue and I will attach a sample project.

**Comment by webron** [comment] 2015-07-05 12:55
@CSchulz - thanks for opening the issue on Jackson, I was away for a while. We'll follow up on it.

**Comment by fehguy** [comment] 2015-10-19 22:59
Please see #1502 for info on configuring the ObjectMapper for Jackson JAXB annotation support.

**Closed by fehguy** 2015-10-19 22:59 UTC
Labels: Documentation

**Comment by aymittal** [comment] 2016-01-19 10:45
@Poohie can you share the bootstrap servlet

**Comment by billforward-alex** [comment] 2016-01-20 19:20
@aymittal

Maybe you can use the servlet I used:

```java
package com.api.rest.cool.my.base;

import com.fasterxml.jackson.module.jaxb.JaxbAnnotationModule;
import io.swagger.jaxrs.config.BeanConfig;
import io.swagger.util.Json;

import javax.servlet.ServletConfig;
import javax.servlet.ServletException;
import javax.servlet.http.HttpServlet;

public class SwaggerBootstrapper extends HttpServlet {
    @Override
    public void init(ServletConfig config) throws ServletException {
        super.init(config);
        
        // this makes Swagger honor JAXB annotations
        Json.mapper()
                .registerModule(new JaxbAnnotationModule());

        BeanConfig beanConfig = new BeanConfig();
        beanConfig.setTitle("My cool REST API");
        beanConfig.setVersion("1.0.0");
        beanConfig.setSchemes(new String[]{"https"});
        beanConfig.setHost("localhost:8080");
        beanConfig.setBasePath("/RestAPI");
        beanConfig.setResourcePackage("com.api.rest.cool.my");
        beanConfig.setScan(true);
    }
}
```

Once I added the line `Json.mapper().registerModule(new JaxbAnnotationModule());` (as per @webron's comment), Swagger started listening to my `@XmlTransient` annotations — that is, it correctly started interpreting those annotations as meaning "hidden = true" .

**Comment by aymittal** [comment] 2016-01-21 03:24
@billforward-alex tried that and still no luck.

**Comment by billforward-alex** [comment] 2016-01-22 09:31
@aymittal I'm surprised that didn't work for you; it's working well on my end. I'm afraid I don't have any other ideas.

**Comment by aymittal** [comment] 2016-01-22 09:36
@billforward-alex what version of swagger are you using?

**Comment by billforward-alex** [comment] 2016-01-22 09:51
@aymittal I am using:

```xml
<dependencies>
<dependency>
		<groupId>${swagger-group}</groupId>
		<artifactId>swagger-jaxrs</artifactId>
		<version>${swagger-version}</version>
	</dependency>
	<dependency>
		<groupId>${swagger-group}</groupId>
		<artifactId>swagger-core</artifactId>
		<version>${swagger-version}</version>
	</dependency>
	<dependency>
		<groupId>${swagger-group}</groupId>
		<artifactId>swagger-annotations</artifactId>
		<version>${swagger-version}</version>
	</dependency>
	<dependency>
		<groupId>${swagger-group}</groupId>
		<artifactId>swagger-models</artifactId>
		<version>${swagger-version}</version>
	</dependency>
</dependencies>
<properties>
	<swagger-version>1.5.6</swagger-version>
	<swagger-group>io.swagger</swagger-group>
</properties>
```

**Comment by aymittal** [comment] 2016-01-22 10:02
@billforward-alex No luck still :(

**Comment by billforward-alex** [comment] 2016-01-22 10:06
@aymittal 

The only other parts of my setup are:

From my Spring `web.xml`:

```xml
<servlet>
    <servlet-name>SwaggerBootstrap</servlet-name>
    <servlet-class>com.api.rest.cool.my.base.SwaggerBootstrapper</servlet-class>
    <load-on-startup>2</load-on-startup>
</servlet>
```

I believe the servlet there *must* be named `SwaggerBootstrap`.

Finally, from my Spring MVC `applicationContext.xml`:

```xml
<bean id="apiListingResource" class="io.swagger.jaxrs.listing.ApiListingResource"/>
<bean id="swaggerSerializers" class="io.swagger.jaxrs.listing.SwaggerSerializers" scope="singleton"/>
```

**Comment by aymittal** [comment] 2016-01-22 10:16
@billforward-alex thanks for your help but still not working.

**Comment by billforward-alex** [comment] 2016-01-22 10:19
@aymittal :( have you tried putting some breakpoints in to double-check that your `SwaggerBootstrap` servlet actually gets hit?

Also if you've got debug symbols or a decompiler, it's worth stepping through `swagger-core`'s internals to see what it's doing.

**Comment by aymittal** [comment] 2016-01-22 10:21
@billforward-alex yes, swaggerbootstrap is getting initialized. i have checked that.

**Comment by CSchulz** [comment] 2016-01-22 10:36
@fehguy Is there a difference between using the JaxbAnnotationIntrospector and the JaxbAnnotationModule?

```
        Json.mapper().registerModule(new JaxbAnnotationModule());
```
vs
```
        AnnotationIntrospector primary = new JacksonAnnotationIntrospector();
        AnnotationIntrospector secondary = new JaxbAnnotationIntrospector(TypeFactory.defaultInstance());
        AnnotationIntrospector pair = AnnotationIntrospector.pair(primary, secondary);
        Json.mapper().setAnnotationIntrospector(pair);
```

**Comment by fehguy** [comment] 2016-01-22 18:01
I know there is, but to be honest I don't recall.  I'd suggest following the technique in swagger-samples for the appropriate system.

**Comment by aymittal** [comment] 2016-01-28 06:28
Soved the issue. Just exclude the following dependencies from swagger dependency.

`<exclusion>`
`<groupId>com.fasterxml.jackson.jaxrs</groupId>`
`<artifactId>jackson-jaxrs-json-provider</artifactId>`
`</exclusion>`
`<exclusion>`
`<groupId>com.sun.jersey</groupId>`
`<artifactId>jersey-client</artifactId>`
`</exclusion>`
`<exclusion>`
`<groupId>com.sun.jersey</groupId>`
`<artifactId>jersey-core</artifactId>`
`</exclusion>`
`<exclusion>`
`<groupId>com.sun.jersey</groupId>`
`<artifactId>jersey-server</artifactId>`
`</exclusion>`

After excluding these i was able to resolve this issue.
