### ISSUE TITLE
1.5.x: ApiImplicitParams annotation is ignored

### ISSUE THREAD

**Issue by cppexpert** [swagger-api/swagger-core#905] opened 2015-03-10 17:22 UTC
When I first noticed this bug I thought it happens only when I use `ApiParam` *and* `ApiImplicitParams` at the same time.

Looks like `ApiImplicitParams` is ignored in any case. As result I can't document security token which intercepted by servlet filter earlier.

Here is endpoint

```java
@GET
@Consumes("text/plain")
@Produces(MediaType.APPLICATION_JSON)
@Path("testParams")
@ApiOperation(response = String.class, value = "Returns string with provided parameter")
@ApiImplicitParams({@ApiImplicitParam(name = "token", required = true, dataType = "string", paramType = "query", value = "API token")})
public String testParams(@ApiParam(required = false, value = "ID of timesheet") @QueryParam("id") int id) {}
```

Example project is located at
https://github.com/cppexpert/broken_swagger_jaxrs_integration

**Comment by webron** [comment] 2015-03-10 17:42
Will check that, but spec-wise, you're probably better off describing it as a security definition and not as an operation parameter.

**Comment by cppexpert** [comment] 2015-03-10 17:46
According to earlier conversation here (in another issue) security definition is not going to work for me for multiple reasons one of which is lack of support of unauthenticated endpoints.

**Comment by webron** [comment] 2015-03-10 17:46
Can you refer me to that discussion please?

**Comment by cppexpert** [comment] 2015-03-10 17:49
https://github.com/swagger-api/swagger-core/issues/889

And even "api_key" wasn't working in my sample app anyway. Filling out that field in swagger-ui never passed it with the request.

**Comment by cppexpert** [comment] 2015-03-14 15:18
Hi Ron! Could you please tell me what rough ETA for the fix is ?
Thanks!

**Comment by webron** [comment] 2015-03-14 15:23
A release should be around next weekend. The fix may be available earlier via a snapshot.

**Comment by cppexpert** [comment] 2015-03-23 19:21
How is it going with new release, guys ? This bug is quite critical too
https://github.com/swagger-api/swagger-core/issues/847

**Comment by fehguy** [comment] 2015-03-23 19:42
Hi @cppexpert M2 is off by a week.  I can certainly do a point release of M1.

Watch for 1.5.3-M1 in a bit.

**Comment by fehguy** [comment] 2015-03-23 20:16
1.5.3-M1 is now released.  It should appear in maven central shortly

**Comment by cppexpert** [comment] 2015-03-23 20:17
But neither #847 nor #905 are fixed in 1.5.3-M1, right ?

**Comment by fehguy** [comment] 2015-03-23 20:19
Implicit params are supported (was the original issue posted here).  Did you look at the fix in the sample project you provided?

The model issue #847 is not quite done yet.

**Comment by cppexpert** [comment] 2015-04-06 15:56
I tried using 1.5.3-M1 with my work project. Implicit parameters are still not visible.

**Comment by sanchopancho13** [comment] 2015-04-07 01:30
I am having the same problem with the ApiImplicitParam annotation.  I spent some time looking over the latest code (1.5.0-M2) and couldn't see any references to this annotation in any of the source code.  I did see a reference in the old 1.3.12 code (in the JaxrsApiReader.scala class).  I think the equivalent class for 1.5 would be the Reader class, but couldn't find an equivalent code block.

**Comment by fehguy** [comment] 2015-04-07 01:57
This implicit parameter code path should be well tested. If you can please provide an example of what is not working we can figure it out.

**Comment by sanchopancho13** [comment] 2015-04-07 04:52
Hi @fehguy.  The simplest test I could devise was the following:

1) Downloaded the latest swagger-core code from master (which is currently 1.5.1-M2).
2) In the samples/java-jaxrs project, edited the `PetResource` class by adding the following annotation to the `getPetById` method:
```java
  @ApiImplicitParams({
	  @ApiImplicitParam(name = "sort", paramType = "query", dataType = "string", required = false, value = "Comma-delimited list of fields to sort by.")
  })
```
3) [I also changed the description of the operation to make sure that I was seeing my latest changes.]
4) Ran the sample project with the maven jetty command.
5) Viewed the new documentation in a local swagger-ui instance.  The implicit parameter is not displayed.

**Comment by buremba** [comment] 2015-04-24 20:29
Any update on this issue? It seems that there is no reference of @ApiImplicitParams in source code even though the documentation is complete.

**Comment by fehguy** [comment] 2015-04-24 20:30
Yes, it's a defect.  Working on it.

**Comment by who** [comment] 2015-05-14 06:28
Any update on this?  Can I help at all ?

**Comment by webron** [comment] 2015-05-14 08:51
It will be handled soon.

**Comment by thegreatdao** [comment] 2015-05-19 16:51
sorry, maybe a bit off the topic, I also ran  into an issue with @ApiParam swagger-core 1.5.1-M2. I wrote a customized SwaggerSpecFilter to filter out some internal param. Whenever I tried to access the "access" property of Parameter in method isParamAllowed, it's alway null. Is this feature missing in 1.5.1-M2? 

Thanks,

**Comment by alexworden** [comment] 2015-05-19 17:07
Can anyone offer insight on where the fix needs to happen? I need this a.s.a.p. and am happy to fix it myself but some pointers in the right direction would greatly help.

**Comment by webron** [comment] 2015-05-19 17:10
It's a whole set of logic that needs to he added to the Reader.java.

**Comment by cppexpert** [comment] 2015-05-19 17:12
@webron How is the progress by the way? It's been two months :)

**Comment by webron** [comment] 2015-05-19 17:14
It's going great, thank you :) Seriously though, I believe we could get it done next week. This week may prove to be difficult.

**Comment by olensmar** [comment] 2015-05-19 18:49
I'm currently doing some stuff in the Reader for another issue, if you can bring me up to speed on this one I can probably fix it as well...

**Comment by webron** [comment] 2015-05-19 18:51
@olensmar - sure, we'll talk about it offline

**Comment by olensmar** [comment] 2015-05-28 12:45
initial code is at https://github.com/swagger-api/swagger-core/compare/develop_2.0...issue-905-implicit-params - please let me know what I missed...

**Comment by webron** [comment] 2015-06-03 19:13
This is now merged in develop_2.0. Will be released soon.

**Closed by webron** 2015-06-03 19:13 UTC
Labels: Bug, P1

**Comment by cppexpert** [comment] 2015-06-03 19:17
Wow, I'll get wasted today if it works.

**Comment by webron** [comment] 2015-06-03 19:18
Haha, it should work, but if you can test the develop_2.0 branch quickly and provide us feedback, that would be great because we want to make a public release very soon.

**Comment by olensmar** [comment] 2015-06-03 19:22
yeah - feedback would be awesome - thanks!

**Comment by alexworden** [comment] 2015-06-03 22:01
I'll try to test it today and will let you know.

**Comment by webron** [comment] 2015-06-03 22:02
@alexworden - thanks!

**Comment by alexworden** [comment] 2015-06-08 23:00
I tried to verify today but I'm using the swagger-maven-plugin to build the
spec at compile time.
Currently, I can't get that project to build, so I can't update the version
of swagger it uses.

I don't have time to spin my wheels in this right now sorry.

**Comment by prota** [comment] 2015-07-10 08:02
Hi all, I'm also experiencing that issue with swagger-play2 version 1.3.12. When do you think it could be fixed?

Thanks

**Comment by webron** [comment] 2015-07-10 08:42
@prota - this is unrelated. The issue is on the 1.5.X branch. Unfortunately, we no longer issue new releases for the 1.3.X branch.

**Comment by cppexpert** [comment] 2015-07-10 09:38
@webron Just to let you know. I just tested `"io.swagger" % "swagger-jersey2-jaxrs" % "1.5.0"` and `ApiImplicitParams` is still not working.

Here is json I get
http://dpaste.com/3CNDBYE

Here is one of the classes defined

```java
@SuppressWarnings("VoidMethodAnnotatedWithGET")
@Path("taskSchedule")
@Api(value = "taskSchedule", description = "Operations with scheduled resources", produces = "application/json")
@Authenticated
public class TaskScheduleRoutes extends AbstractRoutes {

    @GET
    @Consumes(MediaType.APPLICATION_JSON)
    @Produces(MediaType.APPLICATION_JSON)
    @ApiOperation(response = ListResponseWithUpdate.ModifiedTimesheetEntriesResponse.class, value = "Returns multiple task schedules")
    @ApiImplicitParams({@ApiImplicitParam(name = "token", required = true, dataType = "string", paramType = "query", value = "API token")})
    @ManagedAsync
    public ListResponse<TaskScheduleWire> getTaskSchedules(
            @ApiParam(required = true, value = "Comma separated IDs of task schedules") @QueryParam("ids") String idsStr,
            @Suspended final AsyncResponse response) {

        Precondition.checkArgument(idsStr != null && !idsStr.isEmpty(), "`ids` is missing or empty");

        final ArrayList<String> ids = Lists.newArrayList(idsStr.split(","));

        // Basic sanity check
        Precondition.checkArgument(ids.size() > 0, "Array with IDs is empty or not provided");

        return handleInFuture(() -> {
            Collection<TaskSchedule> items = api.getTaskSchedules(ids.stream().map(Long::valueOf).collect(toSet()));
            return new ListResponse<>(items.stream().map(TaskScheduleWire::fromTaskSchedule).collect(toList()));
        }, response);
    }
}
```

Any thought when it can finally be fixed ?

**Comment by webron** [comment] 2015-07-10 09:51
Considering others have reported other bugs related to `@ApiImplicitParam`, it means that they are now successfully scanned and processed (definitely not ignored). If you're still experiencing an issue, feel free to open a new ticket and we'll see how we can investigate it.

**Comment by cppexpert** [comment] 2015-07-10 09:53
@webron Why should I file new ticket if from my POV it's being ignored. I don't and can't know whether it's "really scanned" in the library. All I see is that `token` param is not presented in generated Swagger json.

**Comment by webron** [comment] 2015-07-10 10:20
I took the sample you shared in the original post, updated the dependencies, package names and imports, and it loads the implicit parameter just fine. You may have missed something in the process, I don't know what. Make sure you update the web.xml as well (com.wordnik.swagger... -> io.swagger...).

**Comment by cppexpert** [comment] 2015-07-10 11:02
Sadly I can't have it get initialized now. I get following exception

```json
{
  "error": {
    "type": "GenericException",
    "message": "NotFoundException: HTTP 404 Not Found",
    "stackTrace": "javax.ws.rs.NotFoundException: HTTP 404 Not Found\r\n\tat org.glassfish.jersey.server.ServerRuntime$2.run(ServerRuntime.java:305)\r\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)\r\n\tat org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)\r\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:315)\r\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:297)\r\n\tat org.glassfish.jersey.internal.Errors.process(Errors.java:267)\r\n\tat org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:317)\r\n\tat org.glassfish.jersey.server.ServerRuntime.process(ServerRuntime.java:291)\r\n\tat org.glassfish.jersey.server.ApplicationHandler.handle(ApplicationHandler.java:1140)\r\n\tat org.glassfish.jersey.servlet.WebComponent.service(WebComponent.java:403)\r\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:386)\r\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:334)\r\n\tat org.glassfish.jersey.servlet.ServletContainer.service(ServletContainer.java:221)\r\n\tat org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:751)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1666)\r\n\tat org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)\r\n\tat org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)\r\n\tat org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)\r\n\tat org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:381)\r\n\tat org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1636)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:564)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:143)\r\n\tat org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:578)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1111)\r\n\tat org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:498)\r\n\tat org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:183)\r\n\tat org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1045)\r\n\tat org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)\r\n\tat org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:199)\r\n\tat org.eclipse.jetty.server.handler.HandlerCollection.handle(HandlerCollection.java:109)\r\n\tat org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:98)\r\n\tat org.eclipse.jetty.server.Server.handle(Server.java:461)\r\n\tat org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:284)\r\n\tat org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:244)\r\n\tat org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:534)\r\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:607)\r\n\tat org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:536)\r\n\tat java.lang.Thread.run(Thread.java:745)\r\n"
  }
}
```

Also I see in the debugger that this class `io.swagger.jaxrs.listing.ApiListingResource` is never invoked. Could it be regression of this bug https://github.com/swagger-api/swagger-core/issues/862 ?

My `web.xml` has this

```xml
    <servlet>
        <servlet-name>DefaultJaxrsConfig</servlet-name>
        <servlet-class>io.swagger.jaxrs.config.DefaultJaxrsConfig</servlet-class>
        <init-param>
            <param-name>api.version</param-name>
            <param-value>1.0.0</param-value>
        </init-param>
        <load-on-startup>2</load-on-startup>
    </servlet>
```

and `ResourceConfig` has this

```java
        packages("com.company.api2", "io.swagger.jaxrs.listing");
```

**Comment by fehguy** [comment] 2015-07-13 21:38
@cppexpert I think your dependency isn't right.  Please try this:

```
"io.swagger" % "swagger-jersey2-jaxrs" % "1.5.1-SNAPSHOT"
```

That is where the fix lives.  Let us know?

**Comment by cppexpert** [comment] 2015-07-13 22:15
@fehguy Is there custom repo I can point to ? It's not in genereal maven repo.

**Comment by fehguy** [comment] 2015-07-13 22:23
Yes, please try sonatype snapshots:

```
"sonatype-snapshots" at "https://oss.sonatype.org/content/repositories/snapshots"
```

**Comment by webron** [comment] 2015-07-14 06:56
Actually, the fix is available in 1.5.0.

**Comment by cppexpert** [comment] 2015-07-17 11:23
@fehguy Tony, for some reason it can't fetch `swagger-models`. Perhaps there is wrong reference in parent POM ? Here is what SBT says

```
[warn] ==== sonatype-snapshots: tried
[warn]   https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-models/1.5.1-SNAPSHOT/swagger-models-1.5.1-20150716.064150-10.pom
[warn]   https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-models/1.5.1-SNAPSHOT/swagger-models-1.5.1-SNAPSHOT.pom
[warn] ==== spray releases: tried
```

**Comment by fehguy** [comment] 2015-07-20 16:12
I do see it here:

https://oss.sonatype.org/content/repositories/snapshots/io/swagger/swagger-models/1.5.1-SNAPSHOT/

I'll republish the snapshot though.  Try again?

**Comment by cppexpert** [comment] 2015-07-28 17:41
It works! Thanks!

**Comment by titiu7** [comment] 2015-08-03 16:19
@cppexpert, I tried all the solutions I could find to make the @ApiImplicitParam work, but I have failed. I'm using swagger-jersey-jaxrs 1.5.3-M1. Which version have you used to make it work?

**Comment by cppexpert** [comment] 2015-08-03 17:19
@titiu7 I'm on `"io.swagger" % "swagger-jersey2-jaxrs" %  "1.5.1-SNAPSHOT"` from sonatype snapshots. Just to confuse everyone even more they published latest build with changed package name and _lower_ version number :)

**Comment by titiu7** [comment] 2015-08-04 16:40
@cppexpert it's confusing for sure. I changed the group id to io.swagger and it works. Thanks

**Comment by Michael-crazyman** [comment] 2016-12-22 07:16
I just wanna know in annotation @ApiImplicitParam how to describe a parameter's length.Such as there is a  parameter is String and I wanna the client who send a request know what is the max length and min length of this string by swagger? Thank you.
