### ISSUE TITLE
Add support for JSR-303 constraint annotations

### ISSUE THREAD

**Issue by jasonchaffee** [swagger-api/swagger-core#981] opened 2015-04-13 22:47 UTC
It would be nice if swagger could handle these annotations in both the model and the resource as path, query, and/or matrix params. Currently, it handles the @NotNull annotation and marks the field and/or parameter as required. However, it would be nice if it also handled the other annotations and added the appropriate metadata to the spec. for them. For example, I might have a @Max(50) @Min(0) Integer myNum path/query parameter. The swagger produced JSON could contain information about the constraint that i t must be 0 <= myNum <= 50. Then, the clients of the spec. could do proper validation on their side...such as the swagger-ui and save a round-trip to the server.

See http://docs.oracle.com/javaee/7/api/javax/validation/constraints/package-summary.html for a list of standard annotations that could be used.

**Comment by adrianbk** [comment] 2015-04-13 23:29
Some history on this:
https://github.com/springfox/springfox/issues/356
https://github.com/springfox/springfox/issues/311

As far as I can tell none of the JSR-303 constraint's are supported (including @NotNull).
It should be relatively straight forward to offer rudimentary support for these constraints but we would have to provide a way to disable the feature because there are scenarios, such as using [groups](https://docs.jboss.org/hibernate/validator/4.1/reference/en-US/html/validator-usingvalidator.html#validator-usingvalidator-validationgroups) to conditionally apply validation rules based on runtime conditions, where it is not feasible to try to infer validation constraints.    

@jasonchaffee would you be interesting in contributing to your idea?

**Comment by fehguy** [comment] 2015-04-13 23:46
Hi @jasonchaffee, we have two methods for handling JSR-303:

[ModelResolver.java](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/com/wordnik/swagger/jackson/ModelResolver.java) will process `javax.validation.contraints` annotations directly in swagger-core.  Please see [BeanValidatorTest.scala](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/scala/BeanValidatorTest.scala) for a test of [BeanValidationsModel.java](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/test/scala/models/BeanValidationsModel.java)

For handling hibernate-specific extensions, we've created [modules/swagger-hiberate-validations](https://github.com/swagger-api/swagger-core/tree/master/modules/swagger-hiberate-validations)

and tests which add additional support for scanning hibernate extensions.  Simply include the module and it'll be picked up by SPI.

If there's an annotation missing, please file a ticket with those specific.

**Comment by jasonchaffee** [comment] 2015-04-14 01:12
This works for constraints on the model, but the issue I filed is for support for path params, query params, and matrix params on the resource.  I can use the validations on the query param to make sure that the query param field is within a max and min.  This should be then reflected in the query param in swagger, but I am not seeing that happen.

**Comment by webron** [comment] 2015-04-29 11:05
This is a duplicate of #800.

**Closed by webron** 2015-04-29 11:05 UTC
