### ISSUE TITLE
An exception occurred during processing of the com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON class

### ISSUE THREAD

**Issue by SuperMarioX** [swagger-api/swagger-core#1109] opened 2015-05-28 09:59 UTC
Using swagger + jaxrs and pom.xml is configed successfully.
1. In myapp.java, 
```java
		services.add(com.wordnik.swagger.jaxrs.listing.ApiDeclarationProvider.class);
		services.add(com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON.class);
		services.add(com.wordnik.swagger.jaxrs.listing.ResourceListingProvider.class);
```
2. in web.xml
servelet config is configed as below.
```xml
 <servlet>
<servlet-name>TitanAppServiceSwaggerConfig</servlet-name>
<servlet-class>com.TitanAppServiceSwaggerConfig</servlet-class>
<load-on-startup>1</load-on-startup>
</servlet>
```
3. in my servlet class, using Beanconfig class config the swagger

While I run my app on liberty, I got this error and could not list the json.
```
[ERROR   ] An exception occurred during processing of the com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON class. This class is ignored.
```

Could anyone help me on this issue? Many thanks, :-)

**Comment by webron** [comment] 2015-05-28 13:01
Which version of swagger-core do you use?

**Comment by SuperMarioX** [comment] 2015-05-28 14:03
2.10

**Comment by webron** [comment] 2015-05-28 14:06
That's the scala version, but it also means you're using the 1.3.X branch.

I assume this is a new integration - you should use the 1.5 branch. The wiki contains a few guides for integration. Even though there isn't one for wink, the integration would be very similar to any of the other guides out there and the steps would be very simple (there's a wink sample in the develop_2.0 branch).

Try that and report back if you have any issues.

**Comment by SuperMarioX** [comment] 2015-05-28 14:29
Thanks webron. I have fixed this issue by following closely the guide without servlet. But while integrating with other similar projects, this issue remains if I choose servlet way. I am not sure, but I finally got a way to run it successfully.

**Comment by webron** [comment] 2015-05-28 14:31
Well, there are some issues with Liberty but since that's a commercial product, we don't have access to it for testing.

One thing to keep in mind that since the same configuration works with other app server but not with Liberty, it's more likely that the issue is with Liberty itself.

Can we close the issue?

**Comment by SuperMarioX** [comment] 2015-05-28 14:38
Yes, Config swagger on liberty is a headache and always cause issues. But I think we will find a walkaround. Pls close it and many thanks.

**Closed** 2015-05-28 14:39 UTC
Labels: Awaiting Feedback, Support
