### ISSUE TITLE
Current petstore's pet api declaration violates 1.2 spec.

### ISSUE THREAD

**Issue by prat0318** [swagger-api/swagger-core#890] opened 2015-03-02 21:58 UTC
The [petstore's pet](http://petstore.swagger.io/api/api-docs/pet) api has a path `/pet/uploadImage` which has a parameter `file` of type 'File' but of `paramType` `body` (instead of `form`) which violates the 3rd line of [spec](https://github.com/swagger-api/swagger-spec/blob/master/versions/1.2.md#524-parameter-object)

**Comment by fehguy** [comment] 2015-03-02 22:22
Please send a pull request to the develop_scala-2.10 branch, the sample is from here:

https://github.com/swagger-api/swagger-core/blob/master/samples/scala-oauth-authorization-server/src/main/scala/com/wordnik/swagger/sample/resource/PetResource.scala#L77-L79

**Comment by webron** [comment] 2015-05-28 15:28
Closing as duplicate of #1058 which contains more details.

**Closed by webron** 2015-05-28 15:28 UTC
Labels: Bug, P3
