### ISSUE TITLE
swagger-core does work with Jackson 2.7.0

### ISSUE THREAD

**Issue by ilgrosso** [swagger-api/swagger-core#1601] opened 2016-01-13 12:41 UTC
The current master for `swagger-jaxrs` does not work with Jackson 2.7.0 (latest stable version) because such version removes `com.fasterxml.jackson.databind.type.TypeFactory.constructType(Type, Class<?>)` which is used by [Reader](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs/src/main/java/io/swagger/jaxrs/Reader.java#L829).

Please note that, while being built against Jackson 2.4.5, everything works fine up to Jackson 2.6.4, e.g. the former stable version.

**Comment by fehguy** [comment] 2016-01-13 17:52
It's tricky to keep up with the Jacksons, many implementations don't move as fast.

What is the new syntax in 2.7.x?  Is it back compatible?

**Comment by ilgrosso** [comment] 2016-01-14 08:48
It seems that 2.7.0 accidentally removed the method, which is [now back](https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java#L597-L603) and will be available again in 2.7.1, even though deprecated.

By looking at current implementation, though, it seems that the `Class<?>` argument is ignored, so one could replace the current class in Swagger's Reader from

```
final Type type = TypeFactory.defaultInstance().constructType(genericParameterTypes[i], cls);
```

to

```
final Type type = TypeFactory.defaultInstance().constructType(genericParameterTypes[i]);
```

and have this call working with all Jackson variants (once 2.7.1 will be out, naturally).

**Comment by fehguy** [comment] 2016-01-14 20:24
Thank you for investigating.  Let's hold on 2.7.1 then, and I believe it should work as-is?

**Comment by ilgrosso** [comment] 2016-01-14 20:42
If you want to keep using the deprecated method, yes, we can leave as-is: I was suggesting the change above for relying on a non-deprecated method which is also available in older releases.

**Comment by fehguy** [comment] 2016-01-14 20:48
Got it, if the method is available in the 2.4.x libraries, we should change it.  Do you mind sending a PR?

**Comment by ilgrosso** [comment] 2016-01-14 20:50
Not at all, tomorrow morning I'll send it.

**Comment by ilgrosso** [comment] 2016-01-15 08:12
It seems I was wrong: the change proposed above makes at least 1 unit test to fail:

```
scanModelWithGenericType(io.swagger.GenericsTest)  Time elapsed: 0.017 sec  <<< FAILURE!
java.lang.AssertionError: expected object to not be null
        at io.swagger.GenericsTest.scanModelWithGenericType(GenericsTest.java:225
```

so it seems that in 2.7 the change should be invariant (not considering deprecation, though) while in 2.4.6 there is a difference.

I'd leave things as they currently are, then.

**Comment by juergenzimmermann** [comment] 2016-02-01 03:33
Please see https://github.com/FasterXML/jackson-databind/blob/master/src/main/java/com/fasterxml/jackson/databind/type/TypeFactory.java

**Comment by juergenzimmermann** [comment] 2016-02-01 03:46
https://github.com/FasterXML/jackson-databind/issues/1087 addresses the re-introduction of `constructType`

**Comment by ilgrosso** [comment] 2016-02-03 14:05
FYI with Jackson 2.7.1 (fresh release) everything works fine.

**Comment by webron** [comment] 2016-02-03 23:09
Since it was a Jackson issue in the first place, I wonder if we should upgrade now or hold off on it.

**Comment by fehguy** [comment] 2016-02-04 00:37
But good to know that 2.7.1 is fine with swagger-core.

**Comment by todd-richmond** [comment] 2016-02-08 06:35
Unfortunately 2.7.1 and swagger 1.5.6 now work correctly, but 1.5.7 is quite broken. Roughly 1/3 of all values in swagger.json end up as nulls. I also pulled the Jackson 2.7.2 snapshot build with one more fix for the constructType issue, but that does not make a difference

**Comment by fehguy** [comment] 2016-02-08 14:41
Todd, please check the release notes for 1.5.7 to see if the issue is the '@Provider' change we made.

**Comment by todd-richmond** [comment] 2016-02-08 17:58
ah - that is it - definitely not an obvious failure mode as many fields still have expected values. I also had to remove the code that was setting SNAKE_CASE on the io.swagger.util.Json.mapper()

```
    @Provider
    @Produces({MediaType.APPLICATION_JSON})
    private static class JacksonJsonProvider extends JacksonJaxbJsonProvider {
        JacksonJsonProvider(final ObjectMapper mapper) {
            super.setMapper(mapper);
        }
    }


        register(new JacksonJsonProvider(new ObjectMapper()));

**Comment by todd-richmond** [comment] 2016-02-08 18:47
Actually - this doesn't work with a shaded jar or maybe because that causes a different load order. I don't see how a provider can be set based on looking at the code. io.swagger.util.json does not provide a way to set the ObjectMapper because io.swagger.util. ObjectMapperFactory.CreateJson() has no public way to pass in the ObjectMapper - it always forces null which ends up using the Jackson default ObjectMapper()

I also need the default Jackson provider to work in SNAKE_CASE form to translate between java and json keyname conventions. However, Swagger must work in normal mode or else things like basePath get translated incorrectly

**Comment by todd-richmond** [comment] 2016-02-08 20:47
Played around for another couple of hours w/o luck. When running under Eclipse from it's build, I don't need the extra @Provider - swagger.json has all expected elements. However, I cannot get a shaded jar to work under any circumstance with any combination of provider code

I did notice one significant difference running the 2 Swagger releases. Shaded jar w/ 1.5.6 shows an info log for Reflections but 1.5.7 does not. Is there something that is supposed to initiate this that just happened to work automagically before?

> Reflections Reflections took 1691 ms to scan 1 urls, producing 21317 keys and 38210 values

**Comment by fehguy** [comment] 2016-02-09 18:54
Hi @todd-richmond can you provide a simple sample project?

**Comment by todd-richmond** [comment] 2016-02-10 19:34
that will take quite some effort - let me see if it is possible after I ship a release this week

**Comment by jeff9finger** [comment] 2016-03-01 20:45
Will this issue be resolved with jackson being upgraded to 2.7.2?

I also noticed that the joda packages are old. I updated these to 
```
        <joda-version>1.8.1</joda-version>
        <joda-time-version>2.9.2</joda-time-version>
```
as well in my environment.

**Comment by garydgregory** [comment] 2016-03-01 20:54
Note that the current version of Jackson is 2.7.2.

**Comment by todd-richmond** [comment] 2016-03-14 18:35
I spent some time today attempting to see if 1.5.8 solved my problem (it didn't), but went through the integration docs again and decided to move my Swagger() object creation to my ResourceConfig based constructor as well as register(ApiListingResource.class) and SwaggerSerializers directly. Everything now works as expected for my embedded jetty app even when shaded.

Jackson 2.7.2 is out so I think this bug can be closed

**Comment by fehguy** [comment] 2016-12-25 06:29
Master is upgraded to 2.8.4.

**Closed by fehguy** 2016-12-25 06:29 UTC

**Comment by eduramiba** [comment] 2017-08-22 15:22
This seems to be broken again with Jackson 2.9.0.

Unhandled exception: java.lang.NoSuchMethodError: com.fasterxml.jackson.databind.introspect.AnnotatedMember.annotations()Ljava/lang/Iterable;
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:379)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:236)
	at io.swagger.jackson.ModelResolver.resolve(ModelResolver.java:185)
	at io.swagger.converter.ModelConverterContextImpl.resolve(ModelConverterContextImpl.java:100)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:161)
	at io.swagger.jackson.ModelResolver.resolveProperty(ModelResolver.java:112)
	at io.swagger.converter.ModelConverterContextImpl.resolveProperty(ModelConverterContextImpl.java:80)
	at io.swagger.converter.ModelConverters.readAsProperty(ModelConverters.java:58)
	at io.swagger.jaxrs.DefaultParameterExtension.createProperty(DefaultParameterExtension.java:204)
	at io.swagger.jaxrs.DefaultParameterExtension.extractParameters(DefaultParameterExtension.java:75)
	at io.swagger.jaxrs.ext.AbstractSwaggerExtension.extractParameters(AbstractSwaggerExtension.java:33)
	at io.swagger.jersey.SwaggerJersey2Jaxrs.extractParameters(SwaggerJersey2Jaxrs.java:63)
	at io.swagger.jaxrs.Reader.getParameters(Reader.java:1036)
	at io.swagger.jaxrs.Reader.parseMethod(Reader.java:975)
	at io.swagger.jaxrs.Reader.read(Reader.java:322)
	at io.swagger.jaxrs.Reader.read(Reader.java:172)
	at io.swagger.jaxrs.listing.BaseApiListingResource.scan(BaseApiListingResource.java:65)
	at io.swagger.jaxrs.listing.BaseApiListingResource.process(BaseApiListingResource.java:122)
	at io.swagger.jaxrs.listing.BaseApiListingResource.getListingJsonResponse(BaseApiListingResource.java:167)
	at io.swagger.jaxrs.listing.ApiListingResource.getListing(ApiListingResource.java:33)

Jackson 2.8.9 works fine

**Comment by ilgrosso** [comment] 2017-08-22 15:26
@eduramiba got the same

**Comment by jcalcote** [comment] 2017-09-07 21:43
https://github.com/FasterXML/jackson-core/issues/395

This is likely the cause of the problem in 2.9.0. I'm having it too - can we get swagger updated to use the new 2.9.0 api?

**Comment by eduramiba** [comment] 2017-09-08 09:47
Works fine again with jackson 2.9.1

**Comment by jcalcote** [comment] 2017-09-08 19:37
Well, then I guess we'll have to stick with 2.8.9 until 2.9.1 is published (it's not found on maven central).
