### ISSUE TITLE
@Tag annotation not work as expected on the Controller class.

### ISSUE THREAD

**Issue by scruel** [swagger-api/swagger-core#3826] opened 2020-12-06 13:26 UTC
It seems you decided to replace the old annotation `@Api` by `@Tag`, So after I read the docs of the `@Tag` class, I noticed that you described that "The annotation may be applied at class or method level, ..., for all operations of a class (when applied at class level)".
But when I tried to put this annotation on the Controller class like this:
```
@Tag(name = "test", description = "test")
public class IndexController 
```
It would not work as expected, the operations of the `IndexController` class would not apply the tag info which I applied on class.
I have to put `@Tag` annotation on all operations with same tag info one by one to achieve the goal of 'for all operations'. Otherwise, I will get two tag separately, which called 'index-controller' and 'test'. The 'test' tag will only contain the operations which putted on the same name `@Tag` annotation, the 'index-controller' tag will have the remains like this:
![图片](https://user-images.githubusercontent.com/16933298/101281399-9cb68300-3809-11eb-9d36-5757f23f8d44.png)

**Comment by frantuma** [comment] 2020-12-06 21:07
I cannot reproduce this issue, see e.g. [this test](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-jaxrs2/src/test/java/io/swagger/v3/jaxrs2/ReaderTest.java#L304-L314)

Please provide a reproducible test case if you're still experiencing issues, otherwise please close ticket

**Comment by scruel** [comment] 2020-12-07 00:35
https://github.com/scruel/demo

**Comment by frantuma** [comment] 2020-12-07 07:59
This is a springfox based project, not using spring-core for operation resolving, but its own mechanism. Please open a ticket there

**Closed** 2020-12-08 11:32 UTC
