### ISSUE TITLE
still using jcenter

### ISSUE THREAD

**Issue by chris-brace** [swagger-api/swagger-core#4095] opened 2022-01-12 16:14 UTC
Nearly one year ago gradle and others issued guidance to stop using jcenter(). https://blog.gradle.org/jcenter-shutdown This plugin is still there and is now breaking CI because it cant be retrieved

```
A problem occurred configuring project ':backend:oas3-annotationprocessor:demo'.
> Could not resolve all artifacts for configuration ':backend:oas3-annotationprocessor:demo:classpath'.
   > Could not resolve io.swagger.core.v3:swagger-gradle-plugin:2.1.12.
     Required by:
         project :backend:oas3-annotationprocessor:demo > io.swagger.core.v3.swagger-gradle-plugin:io.swagger.core.v3.swagger-gradle-plugin.gradle.plugin:2.1.12
      > Could not resolve io.swagger.core.v3:swagger-gradle-plugin:2.1.12.
         > Could not get resource 'https://plugins.gradle.org/m2/io/swagger/core/v3/swagger-gradle-plugin/2.1.12/swagger-gradle-plugin-2.1.12.module'.
            > Could not GET 'https://jcenter.bintray.com/io/swagger/core/v3/swagger-gradle-plugin/2.1.12/swagger-gradle-plugin-2.1.12.module'. Received status code 502 from server: Bad Gateway
```

**Comment by natebranchapp** [comment] 2022-01-12 16:30
Came here to same we are experiencing the same issue.

**Comment by chris-brace** [comment] 2022-01-12 17:14
one thing of note, it appears that https://plugins.gradle.org/m2/io/swagger/core/v3/swagger-gradle-plugin/2.1.12/swagger-gradle-plugin-2.1.12.module is redirecting to jcenter. i guess it's possible that this is an issue with the plugin portal but its difficult for me to tell. especially since the rest of our plugins are working fine.

**Comment by mtyeh411** [comment] 2022-01-12 17:21
this needs to be removed, no? not sure what else tbh
https://github.com/swagger-api/swagger-core/blob/v2.1.12/modules/swagger-gradle-plugin/build.gradle#L18

**Comment by mtyeh411** [comment] 2022-01-12 17:52
we've circumvented this issue for now by resolving plugin from Maven Central
https://docs.gradle.org/current/userguide/plugins.html#sec:custom_plugin_repositories

**Comment by chris-brace** [comment] 2022-01-12 18:42
> this needs to be removed, no? not sure what else tbh https://github.com/swagger-api/swagger-core/blob/v2.1.12/modules/swagger-gradle-plugin/build.gradle#L18

yeah i cant tell what causes the plugin to be in jcenter or if that line you linked to determines what gradles plugin publisher does

**Comment by chris-brace** [comment] 2022-01-12 19:30
The mirror redirect appears to be a gradle issue https://status.gradle.com

I fixed this for the mean time by building the gradle plugin on my own and publishing it to a private maven repo we host on s3.

Im going to leave this open because the `jcenter()` line in this build.gradle needs to be removed.

**Comment by Akaame** [comment] 2022-01-19 16:50
Any updates on this issue?

**Comment by frantuma** [comment] 2022-01-24 10:50
Thanks all for reporting this

I am not sure about the cause of the issues with plugin resolution from plugin portal "redirecting" to jcenter (as from some tests I am not experiencing issues in plugin 2.1.12 resolution atm), however jcenter() references hav been removed in #4099. 

Closing ticket, please reopen/comment if you're still experiencing issues

**Closed by frantuma** 2022-01-24 10:50 UTC
