### ISSUE TITLE
Value.Immutable

### ISSUE THREAD

**Issue by gokumar** [swagger-api/swagger-core#2084] opened 2017-01-15 05:53 UTC
I am using Value.Immutable classes as part of my rest input/output. Swagger does not seem to understand these beans as there are no getters and setters in the immutable interface definition. Because of this, I don't see anything in the Example section in swagger.

How do I enable Value.Immutable classes?

I am using 1.0.0-1

**Comment by blalasaadri** [comment] 2017-02-20 14:29
Same problem here with Swagger 2.6.1 and [Immutables](https://immutables.github.io/immutable.html) 2.4.3.

**Comment by webron** [comment] 2017-02-20 17:47
What is swagger 2.6.1?

**Comment by blalasaadri** [comment] 2017-02-21 08:39
Ah sorry, my mistake I've corrected my post. It's Swagger v1.5.10.

**Comment by dongshengbc** [comment] 2017-03-10 16:37
Any updates on this?

**Comment by webron** [comment] 2017-03-10 17:44
Any updates on what? The question isn't very clear.

**Comment by dongshengbc** [comment] 2017-03-13 14:05
@webron Thanks for reply. I meant to ask how we could combine using Value.Immutable (immutables.github.io) with swagger? 

Is that a solved problem? That will be great if that is the case.

**Comment by fehguy** [comment] 2017-03-13 15:33
That would introduce another dependency, which we are only doing if absolutely necessary.  So I don't think this falls into that category

**Comment by blalasaadri** [comment] 2017-03-13 16:09
@fehguy Actually, I disagree. Swagger wouldn't need a further dependency; instead there could be a mode where Swagger will scan beans not for fields but rather for getters.

**Comment by fehguy** [comment] 2017-03-13 16:11
which part do you disagree with?

**Comment by blalasaadri** [comment] 2017-03-13 16:11
I disagree with the notion, that solving this problem would introduce a further dependency. The solution doesn't have to be (and probably shouldn't be) specific to Value.Immutables.

**Comment by msmerc** [comment] 2017-03-23 20:33
I have the same issue. It seems that the Jackson `io.swagger.jackson.ModelResolver` expects everything to be bean-like. However it's perfectly possible to stream non-bean methods into XML.

It doesn't look too tricky to fix, the question really is how best to resolve it? I can think of a few ideas:
 

1. Create an Immutable ModelResolver. This is clean but the problem with this is that it would need to see the immutables annotations, which adds a dependency. Is it possible to somehow do this optionally? I've no idea?

2. Refactor the jackson ModelResolver so that it has some extension points - for example you'd want all ModelResolves to respect the swagger annotations.

3. Enhance the jackson ModelResolver so that it will pull in every method, not just bean-like methods. (Or maybe every method that takes no args?)


If someone who knows about swagger / ModelResolvers has any suggestions on how best to provide a solution I don't mind taking a look further (no promises though :p )

**Comment by msmerc** [comment] 2017-03-23 20:58
Upon further inspection, I *think* the root cause here is that the ModelResolver doesn't respect the `@JsonSerialize(as=...)` annotation. If we can add this it might JustWork(tm).

Here's the extra test I'm using (to be added to `SimpleGenerationTest.java`):

    @Test
    public void testNotBeanlike() throws Exception {
        final Model model = context.resolve(NotBeanlike.class);
        final Map<String, Property> props = model.getProperties();
        assertEquals(props.size(), 1);

        final Property prop = props.values().iterator().next();
        assertEquals(prop.getName(), "notGetter");
    }

    static class NotBeanlike {
        @JsonProperty("notGetter")
        public String notGetter() {return "Not a getter";}
    }

    @Test
    public void testEvenLessBeanlike() throws Exception {
        final Model model = context.resolve(EvenLessBeanlike.class);
        final Map<String, Property> props = model.getProperties();
        assertEquals(props.size(), 1);

        final Property prop = props.values().iterator().next();
        assertEquals(prop.getName(), "notGetter");
    }

    @JsonSerialize(as = NotBeanlike.class)
    @JsonDeserialize(as = NotBeanlike.class)
    static interface EvenLessBeanlike {
        public String notGetter();
    }

**Comment by fehguy** [comment] 2017-03-24 16:45
Yes, we do not support the `JsonSerialize(...)` annotation at all.  I also don't want to add another dependency as it creates other messes.

However, for testing purposes, let's go ahead and add the immutables dependency as a test dependency.

Please add a test showing this issue and go ahead and the dependency, we'll see if we can fix it in general.

**Comment by msmerc** [comment] 2017-03-24 17:18
@fehguy I've updated my PR to include an immutables test.

It also has a proposed fix ;)

**Comment by msmerc** [comment] 2017-03-30 15:13
@fehguy Any thoughts?

**Comment by fehguy** [comment] 2017-04-26 09:57
This has been merged, sorry for the delay

**Closed by fehguy** 2017-04-26 09:57 UTC

**Comment by msmerc** [comment] 2017-04-26 10:11
Thanks - much appreciated!

When are you guys next planning to release?

**Comment by fehguy** [comment] 2017-06-13 20:54
1.5.14 has been released:

https://github.com/swagger-api/swagger-core/releases/tag/v1.5.14

**Comment by kingcowman** [comment] 2019-09-10 00:28
@fehguy This feature was removed in 2.0.0, was there a reason for this and was the functionality replaced?

**Comment by webron** [comment] 2019-09-10 00:50
@kingcowman - 2.0.0 was a rewrite almost from scratch, so some features might have dropped. Please file a new ticket and reference this one.
