### ISSUE TITLE
@ApiImplicitParam doesn work correctly on @FormDataParam?!

### ISSUE THREAD

**Issue by thomasmey** [swagger-api/swagger-core#1325] opened 2015-08-05 05:11 UTC
@POST
        @Path("/upload")
        @Consumes({ MediaType.MULTIPART_FORM_DATA })
        @Produces({ MediaType.APPLICATION_JSON })
        @Encoded
        @ApiOperation(value = "Does upload data", notes = "")
        @ApiResponses(value = {
                        @ApiResponse(code = 400, message = "bad request")
        })
        @ApiImplicitParams({
                @ApiImplicitParam(name="meta", required = false, dataType="JSONType", paramType="form", value = "upload metadata")
        })
        public Response upload (
                        @FormDataParam("meta") String uploadMmetadataJson,
                        @ApiParam(value = "Upload data content", required = true )
                        @FormDataParam("content") InputStream content,
                        @FormDataParam("content") FormDataBodyPart formDataBodyPart,
                        @Context HttpServletRequest request
                        ) {

I had the expectation that swagger should show the parameter meta as model "JSONType" but it doesn't. Bug or feature?

Useing Swagger-core and swagger-jersey-jaxrs 1.5.0.

**Comment by webron** [comment] 2015-08-05 13:14
FWIW, a `formData` parameter can't be a complex type.

What *does* it show you?

**Comment by thomasmey** [comment] 2015-08-05 17:10
Yes I know. I declare "meta" as String and do the JSON mapping in the method. But in swagger-ui I want it to show up as complex type JSONType from the swagger model. But it only shows up as String in swagger-ui.

I actually tried to define "meta" as complex type itself and for this I implemented the fromString (see documentation of FormDataParam) method in JSONType class but swagger-ui still showed it as String if I recall correctly.

So any idea how I can display on form data parameter as JSON type in swagger-ui?

**Comment by webron** [comment] 2015-08-05 18:27
You can't. As said, `formData` parameters can't be complex types, only primitives.

**Comment by thomasmey** [comment] 2015-08-09 15:40
That's not true for Jersey 1.x:

See documentation of the jersey multipart extention: https://jersey.java.net/apidocs/1.11/contribs/jersey-multipart/index.html?com/sun/jersey/multipart/FormDataParam.html

"If there is no message body reader available and the type T conforms to a type specified by FormParam then processing is performed as specified by FormParam, where the values of the form parameter are String instances produced by reading the bytes of the named body parts utilizing a message body reader for the String type and the media type "text/plain".

If there is no named part present then processing is performed as specified by FormParam."

And the documentation of FormParam ( https://jersey.java.net/apidocs/1.18/jersey/javax/ws/rs/FormParam.html ).

"The type T of the annotated parameter must be one of the following: 
1.    Be a primitive type
2.    Have a constructor that accepts a single String argument
3.    Have a static method named valueOf or fromString that accepts a single String argument (see, for example, Integer.valueOf(String))
4.    Be List<T>, Set<T> or SortedSet<T>, where T satisfies 2 or 3 above. The resulting collection is read-only."

So the type of formData can be a complex type. Or do I misunderstand somehing here?

So If the type of @FormDataParam is "JSONType"  which is a java class with swagger annotations and either has a constructor of type String or a method "fromString()" Jeresy does correctly transform the body data into a complex type.

Sadly there is now way in swagger-ui to show a formData parameter with as a complex type.

**Comment by fehguy** [comment] 2015-08-09 19:17
Slight clarification to @webron's comment. Swagger spec is not bound solely to any framework including jaxrs. Therefore it is quite possible to have a framework feature which is outside of the spec, this seems to be an example.

**Comment by fehguy** [comment] 2015-08-11 18:45
I'm going to close this as "as designed".  Please open a spec enhancement in swagger-spec if this is too restrictive for you and you have a general proposal for handling it.

**Closed by fehguy** 2015-08-11 18:45 UTC
