### ISSUE TITLE
In jersey annotation, link will be broken if child model is annotated by @ApiModel(value="NewModel")

### ISSUE THREAD

**Issue by hongxingli** [swagger-api/swagger-core#1063] opened 2015-05-12 18:44 UTC
For example we have a jersey 2.0 setup with the following model classes, if we don't annotate AccountModel and UserModel with @ApiModel(value=...), then everything works fine, but when we add those annotations, AccountRegistration will not show up properly in swagger.json and further on swagger UI due to that AccountRegistration will still refer to AccountModel, UserModel, not Account and User.

```java
@ApiModel(value="Account", description = "Account information")
public class AccountModel {
String name;
}
@ApiModel(value="User", description = "User information")
public class UserModel {
String name;
}
@ApiModel(description = "Account registration")
public class AccountRegistration {
AccountModel account;
UserModel user;
}
```

**Comment by webron** [comment] 2015-05-12 18:47
Which version of swagger-core do you use?

**Comment by hongxingli** [comment] 2015-05-12 18:53
Thanks Ron for the quick response, really appreciated! We are using 1.5.3M.

**Comment by webron** [comment] 2015-05-12 18:54
Okay, since I'm not sure if this issue was fixed already or not, can you please upgrade to 1.5.1-M2 and see if it persists?

**Comment by hongxingli** [comment] 2015-05-12 18:55
from the .json, I can see that
....
$ref: "#/definitions/AccountModel"
....
$ref: "#/definitions/AccountModel"

But due to the @ApiModel(value=...) annotation, the model has already been rename to Account and User

**Comment by webron** [comment] 2015-05-12 18:58
Right, the problem is clear. Can you try upgrading?

**Comment by hongxingli** [comment] 2015-05-12 19:01
We are on 1.5.3M1, just tried it on 1.5.1M2, issue is still there. Actually same issue exists in stable release 1.3.12.

**Comment by webron** [comment] 2015-05-12 19:02
Very well, we need to take care of it.

**Comment by hongxingli** [comment] 2015-05-12 20:27
hi Ron, can I ask you a quick question?  what's the difference between 1.5.3-M1 vs 1.5.1-M2?

Thanks, 



     On Tuesday, May 12, 2015 12:02 PM, Ron <notifications@github.com> wrote:
   
 

 Very well, we need to take care of it.—

**Comment by webron** [comment] 2015-05-12 20:29
1.5.1-M2 is the newer release. I don't recall exactly what's new in it.

**Comment by tomtit** [comment] 2015-05-15 12:35
Looks like a duplicate of the #992. On 1.5.2-M2-SNAPSHOT (branch `develop_2.0`) this resource:
```
@Api("renamed")
@Path("renamed")
@Produces({"application/xml"})
public class ResourceWithRenamedModel {

  @GET
  @Path("/test")
  @ApiOperation(value = "Test operation", response = AccountRegistration.class, tags="Test")
  public AccountRegistration test() {
    return null;
  }

  @ApiModel(value = "Account", description = "Account information")
  public static class AccountModel {
    public String name;
  }

  @ApiModel(value = "User", description = "User information")
  public static class UserModel {
    public String name;
  }

  @ApiModel(description = "Account registration")
  public static class AccountRegistration {
    public AccountModel account;
    public UserModel user;
  }
}
```
is reported as follows:
```
{
  "swagger" : "2.0",
  "tags" : [ {
    "name" : "renamed"
  }, {
    "name" : "Test"
  } ],
  "paths" : {
    "/renamed/test" : {
      "get" : {
        "tags" : [ "Test" ],
        "summary" : "Test operation",
        "description" : "",
        "operationId" : "test",
        "produces" : [ "application/xml" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/AccountRegistration"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "User" : {
      "properties" : {
        "name" : {
          "type" : "string"
        }
      },
      "description" : "User information"
    },
    "AccountRegistration" : {
      "properties" : {
        "account" : {
          "$ref" : "#/definitions/Account"
        },
        "user" : {
          "$ref" : "#/definitions/User"
        }
      },
      "description" : "Account registration"
    },
    "Account" : {
      "properties" : {
        "name" : {
          "type" : "string"
        }
      },
      "description" : "Account information"
    }
  }
}
```

**Comment by hongxingli** [comment] 2015-05-15 19:08
hi Alexey,
Thanks for help take a look, yes, it's the same issue, please help close it.
When will it be merged to main branch?
Thanks, 


     On Friday, May 15, 2015 5:35 AM, Alexey Nechaev <notifications@github.com> wrote:
   
 

 Looks like a duplicate of the #992. On 1.5.2-M2-SNAPSHOT (branch develop_2.0) this resource:@Api("renamed")
@Path("renamed")
@Produces({"application/xml"})
public class ResourceWithRenamedModel {

  @GET
  @Path("/test")
  @ApiOperation(value = "Test operation", response = AccountRegistration.class, tags="Test")
  public AccountRegistration test() {
    return null;
  }

  @ApiModel(value = "Account", description = "Account information")
  public static class AccountModel {
    public String name;
  }

  @ApiModel(value = "User", description = "User information")
  public static class UserModel {
    public String name;
  }

  @ApiModel(description = "Account registration")
  public static class AccountRegistration {
    public AccountModel account;
    public UserModel user;
  }
}
is reported as follows:{
  "swagger" : "2.0",
  "tags" : [ {
    "name" : "renamed"
  }, {
    "name" : "Test"
  } ],
  "paths" : {
    "/renamed/test" : {
      "get" : {
        "tags" : [ "Test" ],
        "summary" : "Test operation",
        "description" : "",
        "operationId" : "test",
        "produces" : [ "application/xml" ],
        "parameters" : [ ],
        "responses" : {
          "200" : {
            "description" : "successful operation",
            "schema" : {
              "$ref" : "#/definitions/AccountRegistration"
            }
          }
        }
      }
    }
  },
  "definitions" : {
    "User" : {
      "properties" : {
        "name" : {
          "type" : "string"
        }
      },
      "description" : "User information"
    },
    "AccountRegistration" : {
      "properties" : {
        "account" : {
          "$ref" : "#/definitions/Account"
        },
        "user" : {
          "$ref" : "#/definitions/User"
        }
      },
      "description" : "Account registration"
    },
    "Account" : {
      "properties" : {
        "name" : {
          "type" : "string"
        }
      },
      "description" : "Account information"
    }
  }
}

**Comment by webron** [comment] 2015-05-16 15:00
Within a couple of weeks.

**Closed by webron** 2015-05-16 15:00 UTC
Labels: Bug, P2
