### ISSUE TITLE
Play Framework 2.4 Update for Swagger-Play2 Plugin.

### ISSUE THREAD

**Issue by mikalveli** [swagger-api/swagger-core#1144] opened 2015-06-08 19:18 UTC
The Swagger-Play2 Plugin is currently broken by the Play 2.4 update. I know there is work taking place to move this out to it's own project, but I figured I could help with a stop gap until then. Here is a link to my branch that updates the plugin to work with Play 2.4.

https://github.com/mikalveli/swagger-core/tree/1.3.12-play2.4

**Comment by jackphel** [comment] 2015-06-10 03:20
@mikalveli are you keeping your fork as a dependency from maven local?

**Comment by mikalveli** [comment] 2015-06-10 11:13
I am, we're just installing to our local repos via sbt publish-local. You just have to change into the swagger-core / modules/swagger-play2 directory and issue the sbt publish-local command. Then just update your sbt dependency version wherever you want to use it to 1.3.12_play24.

**Comment by cablegunmaster** [comment] 2015-06-10 14:54
mikalveli, i'm trying to recreate what you did, because im updating Play to 2.4 as well, with my swagger-core.

1. I clone your repository. Esentially downloading the files in a folder. like D:\Swagger-core
2. I go to the swagger-core folder.
3. I checkout the folder into my local repository of my pc? ( git local). Create my own repository for this?
4. I use the sbt publish-local command to attach the repository with my play framework?

I don't understand step 3 checking out the module on the local pc. 
'1.3.12-play2.4' != '1.3.12_play24'

**Comment by mikalveli** [comment] 2015-06-10 17:04
Hey @cablegunmaster, the command "git checkout 1.3.12-play2.4" is to switch to the branch where I pushed my modifications in the forked repo. Once you change over to the 1.3.12-play2.4 branch with the git checkout command, you will have the modules/swagger-play2 directory where you will navigate to in order to issue the sbt publish-local command.

**Comment by cablegunmaster** [comment] 2015-06-10 21:56
@mikalveli I got the part fixed with checkout and clone :). the publish-local command worked after figuring out how it works. now only to resolve the Swagger update errors ^^! 

    "URI has an authority component"
Windows users: build.scala replace 'file://' 'file:///' to compensate for the location URI error the SBT creates.

Also don't forget to add the local SBT repository in your build.sbt:
    resolvers += Resolver.mavenLocal

**Comment by truman-misfit** [comment] 2015-06-12 10:47
@mikalveli I got a strange error when I follow your steps:
```
type ApiHelpController is not a member of package controllers
```

I figure out that you define `ApiHelpController` as a `Object` instead of `Class` which causes the compilation error. So I change the ApiHelpController to `Class` and it looks good to me. Have I missed something important?

**Comment by truman-misfit** [comment] 2015-06-13 06:41
@mikalveli I got the problem and fixed it. I think the compilation error was caused by the `routesGenerator ` in my `build.sbt` file. Play 2.4, by default, generates a dependency injected router, unlike previously, when it used a static router.

**Comment by matiwinnetou** [comment] 2015-06-13 11:00
I ported 1.3.12 to Play 2.4 here:

https://github.com/matiwinnetou/swagger-play24

**Comment by Ciantic** [comment] 2015-07-01 12:54
Is there plans to support play in the core? I know that the Readme says:

> Future milestone releases will add support for plain Servlets and Play Framework.

But it's been there probably for ages. I'm now trying this @matiwinnetou's implementation.

**Comment by webron** [comment] 2015-07-05 14:51
@Ciantic - there are plans for it, either directly in code or as a separate project. Can't say when though.

**Comment by webron** [comment] 2015-07-13 15:17
Thanks for the great work everyone. I'll close this issue for now. For progress on the Play module, please follow #918.

**Closed by webron** 2015-07-13 15:17 UTC
