### ISSUE TITLE
OperantionId may be duplicated

### ISSUE THREAD

**Issue by cunhazera** [swagger-api/swagger-core#2433] opened 2017-09-18 13:27 UTC
Now a days operationId is generated based on the endpoint method name. So when you have two methods with the same name (even in different classes) it causes a conflict in the swagger.json file.

For example:

``` java
@ApiOperation(value = "Just testing")
@Path("test-one")
public class Test {
    @GET
    @Path("test")
    public Response test() {
        return Response.ok().build();
    }
}
```

``` java
@ApiOperation(value = "Testing...")
@Path("test-two")
public class Test2 {
    @GET
    @Path("another-test")
    public Response test() {
        return Response.ok().build();
    }
}
```

The operationId property in the final file will be `test` for both endpoints.

**Comment by webron** [comment] 2017-09-18 16:17
Which version of swagger-core?

**Comment by cunhazera** [comment] 2017-09-18 16:23
1.5.16

**Comment by sergeijakovlev** [comment] 2017-12-11 15:26
This issue also exists in version swagger-jaxrs version 1.5.17. The part of the Reader class that seems to be responsible is currently the following:

        if (!methodInSuperType) {
            operationId = method.getName();
        } else {
            operationId = this.getOperationId(method.getName());
        }

This code tries to generate a unique operationId if the method is defined for super type to avoid duplicate operationIds when using inheritance for resources (https://github.com/swagger-api/swagger-core/commit/7878cfde405042465dcf3e65135e77ff34b40275). Unfortunately, this is not done for other methods.

Quite obviously, this causes duplicate operationIds to appear if two methods in completely unrelated classes share the same name. In this case it is possible to either rename those methods or supply a custom nickname if methods cannot be renamed.

A bit less obviously, this also causes duplicates when the same sub-resource is used in multiple resources. In that case it is impossible to rename different "copies" of methods or supply different nicknames.

Unfortunately, we currently have the second situation. In our API we have to handle a relatively complex sub-resource common to multiple resources. Currently I do not see a way to avoid semantic errors (operationIds must be unique) in our generated Swagger files.

Is there a reason why you chose specifically _not_ to generate unique IDs for all methods? As far as I can tell, duplicate IDs in swagger files should not exist in any case - why not default to the safe behavior in all cases?

If this is a performance optimization, it must be noted that `String getOperationId(String operationId)` and `boolean existOperationId(String operationId)` seem to be very sub-optimal and iterate over all operations and all paths to check if an operationId is unique, and repeat the process for each subsequent generated ID. It seems that a simple HashMap would go a long way in improving the performance of this particular section.

**Comment by sergeijakovlev** [comment] 2017-12-12 12:38
Unfortunately, I was unable to find documentation regarding expected behavior of the Reader class. Optimizing de-duplication of operationIds is trivial if a Swagger object is expected to be bound to only one Reader at a time, which does not seem to be guaranteed. It seems that re-scanning of all paths is performed in case a Swagger object is modified externally while Reader is working, but currently the code does not seem thread-safe.

**Comment by frantuma** [comment] 2018-02-19 18:05
merged #2671 which applies `getOperationId` logic to all scenarios, closing ticket, please reopen if you're still experiencing issues

**Closed by frantuma** 2018-02-19 18:05 UTC

**Comment by zyro23** [comment] 2018-04-23 15:33
could this fix be applied to swagger-servlet as well?

**Comment by larsf** [comment] 2019-03-31 18:54
This change cause swagger-codegen to generate methods that now have "arbitrary" numbers in the name. So in stead of being able to call "endpoint".delete(), depending on how many endpoints you have, it may be endpoint.delete_1(), or endpoint.delete_100(). When you allowed for the operationId to simply be equal to the method name, the api calls were consistent like this:
firstEndpoint.delete() and secondEndpoint.delete(), instead of now being firstEndpoint.delete_1(), and secondEndpoint.delete_2()

Is there a way to override this auto numbering, and revert to the old behavior?

**Comment by ChristianLutz** [comment] 2019-09-18 09:01
@larsf 

I solved this problem with a filterClass
```
public class OperationIdPrefixFilter extends AbstractSpecFilter {

	@Override
	public Optional<Operation> filterOperation(Operation operation, ApiDescription api, Map<String,
			List<String>> params, Map<String, String> cookies, Map<String, List<String>> headers) {
		String operationId = operation.getOperationId();
		operation.setOperationId(operationId.split("_[0-9]+$")[0]);

		return super.filterOperation(operation, api, params, cookies, headers);
	}
}
```

**Comment by JohnJonnyJohn** [comment] 2019-11-08 14:57
@ChristianLutz 
I have also the same problem and would like to use your filter to archive prefixless operationIds. Can you explain how and where you are adding the OperationIdPrefixFilter class into your project?

**Comment by ChristianLutz** [comment] 2019-11-10 07:45
@JohnJonnyJohn 

You can configure `filterClass` see [here](https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Integration-and-Configuration#configuration-properties)
