### ISSUE TITLE
[swagger-maven-plugin-jakarta] Same OpenAPI used while generating two files in two executions

### ISSUE THREAD

**Issue by agatarychter** [swagger-api/swagger-core#4497] opened 2023-10-17 09:05 UTC
While using following config of the plugin and **2** executions which should result in 2 separate open API generations -> only the first config is taken and both generated files contain the same content. 
Please fix this so that each execution takes their own config and generates the correct API. 
```<plugin>
                <groupId>io.swagger.core.v3</groupId>
                <artifactId>swagger-maven-plugin-jakarta</artifactId>
                <version>2.2.17</version>
                <executions>
                    <execution>
                        <id>id1</id>
                        <configuration>
                            <outputFileName>file1</outputFileName>
                            <outputPath>apis/</outputPath>
                            <outputFormat>JSON</outputFormat>
                            <configurationFilePath>${project.basedir}/src/main/resources/swagger-1-config-file.json</configurationFilePath>
                        </configuration>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                    </execution>
                         <execution>
                        <id>id2</id>
                        <configuration>
                            <outputFileName>file2</outputFileName>
                            <outputPath>apis/</outputPath>
                            <outputFormat>JSON</outputFormat>
                            <configurationFilePath>${project.basedir}/src/main/resources/swagger-2-config-file.json</configurationFilePath>
                        </configuration>
                        <phase>compile</phase>
                        <goals>
                            <goal>resolve</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
```

**Comment by frantuma** [comment] 2023-10-17 10:20
duplicate of [#4471](https://github.com/swagger-api/swagger-core/issues/4471#issuecomment-1706398890)

**Closed by frantuma** 2023-10-17 10:20 UTC
