### ISSUE TITLE
Groovy support broken with last release versions

### ISSUE THREAD

**Issue by ipeluffo** [swagger-api/swagger-core#1181] opened 2015-06-18 13:51 UTC
In a project using Guice, Jersey 1.x and Groovy, Swagger stopped working after updating to the last release version (swagger-jaxrs:1.5.0).

Take a look to the stack trace of the error : http://pastie.org/private/xaz1i8h5p9s729qocj02q

After debugging Swagger code for several hours I reached to the conclusion that the problem is caused by the runtime methods that Groovy adds to every class and the class CompilerConfiguration which has two setters for a single property.

First, I tried adding Groovy packages to be skipped to `ModelConverters` but I found that the method `readAsProperty` [doesn't check for the configured packages](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/converter/ModelConverters.java#L56).

I finally did the following:

``` groovy
class CustomModelResolver extends ModelResolver {

    CustomModelResolver(ObjectMapper mapper) {
      super(mapper)
    }

    @Override
    protected boolean shouldIgnoreClass(Type type) {
      return super.shouldIgnoreClass(type) || type.getTypeName().contains("groovy")
    }
  }
```

``` groovy
def initializeSwaggerModelResolver() {
    def modelConverter = ModelConverters.getInstance()
    modelConverter.addConverter(new CustomModelResolver(Json.mapper()))
  }
```

This customization worked since the `addConverter` method always set a unique ModelResolver. [See method implementation here](https://github.com/swagger-api/swagger-core/blob/master/modules/swagger-core/src/main/java/io/swagger/converter/ModelConverters.java#L38). Then, I consider this implementation a patch and not a final solid solution.

I'd appreciate any feedback about this solution. I'll try to find a more general solution for this issue and make a PR to solve it.

Thanks in advance.
Nacho

**Comment by fehguy** [comment] 2015-08-11 01:14
Hmm, I don't know enough about groovy magic to understand how it injects classes at runtime.  It may be true that adding groovy as an "always ignore package" as you describe in the `ModelResolver.java`.

**Comment by nistvan86** [comment] 2015-10-13 08:14
Had the same issue. Confirmed that it solves the issue with Groovy. Please include this fix in the next release. Maybe a switch in the BeanConfig would be handy to disable the filtering if someone wants to override it.

**Comment by ipeluffo** [comment] 2015-10-13 13:50
I've been very busy lately. I'll try to make the PR to fix this issue asap.

Could anyone confirm me if I'll be able to make the Test case for this fix?

@nistvan86 , I need to do a deeper analysis to see how to add the *switch* in the BeanConfig. Also, this would be useful only for those using the BeanConfig to configure Swagger but not for the ones which don't use it (like me :wink: )

**Comment by fmahnke** [comment] 2016-02-02 18:18
+1. We use Groovy in our project and can't upgrade to the latest swagger.

**Comment by fehguy** [comment] 2016-02-02 18:25
As I mentioned, someone can send a PR and I'd be happy to get it merged.  But the cause and the magic of groovy is not something that's clear to me.

**Closed** 2016-12-25 06:48 UTC
Labels: Feature
