### ISSUE TITLE
Swagger-core Not working with jaxrs-resteasy and CDI

### ISSUE THREAD

**Issue by hiteshgupta33** [swagger-api/swagger-core#1170] opened 2015-06-15 22:20 UTC
I was trying to integrate Swagger in my Rest services. I am using jboss resteasy implementation of jaxrs wirh CDI but Swagger 1.5 doesn't seem to work with it. 

Any idea. I am deploying the services on Jboss eap 6.x

**Comment by webron** [comment] 2015-06-16 06:02
"doesn't seem to work with it" doesn't provide us with information to better understand what doesn't work and what you've done so far. Without more details, we will not be able to help.

**Comment by hiteshgupta33** [comment] 2015-06-16 16:45
@webron  Hi Ron: 
This is my web.xml
<context-param>
		<param-name>resteasy.resources</param-name>
		<param-value>io.swagger.jaxrs.listing.ApiListingResource</param-value>
		<param-value>io.swagger.jaxrs.listing.SwaggerSerializers</param-value>
		<param-value>edu.ucsd.act.academic.ClassWaitlist.rest.WaitlistController</param-value>
	</context-param>
 
 
	<context-param>
		<param-name>resteasy.providers</param-name>
		<param-value>
    			io.swagger.jaxrs.json.JacksonJsonProvider,
      		io.swagger.jaxrs.listing.ApiDeclarationProvider,
    		  io.swagger.jaxrs.listing.ResourceListingProvider
    	</param-value>
	</context-param>
	
	<servlet>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
        <load-on-startup>1</load-on-startup>
    </servlet>
    <servlet-mapping>
        <servlet-name>javax.ws.rs.core.Application</servlet-name>
        <url-pattern>/v1/*</url-pattern>
    </servlet-mapping>
    
  <servlet>
        <servlet-name>DefaultJaxrsConfig</servlet-name>
        <servlet-class>io.swagger.jaxrs.config.DefaultJaxrsConfig</servlet-class>
        <init-param>
            <param-name>api.version</param-name>
            <param-value>1.0.0</param-value>
        </init-param>
        <init-param>
            <param-name>swagger.api.basepath</param-name>
            <param-value>http://localhost:8080/ClassWaitlist</param-value>
        </init-param>
        <load-on-startup>2</load-on-startup>
    </servlet>
	
	<session-config>
		<session-timeout>120</session-timeout>
	</session-config>

swagger dependency in POM.xml 
<dependency>
			<groupId>io.swagger</groupId>
			<artifactId>swagger-jaxrs</artifactId>
			<version>1.5.0</version>
		</dependency>

and also using Jboss jaxrs api 

<dependency>
			<groupId>org.jboss.spec.javax.ws.rs</groupId>
			<artifactId>jboss-jaxrs-api_1.1_spec</artifactId>
			<scope>provided</scope>
		</dependency>
Controller snippet:

@Path("/classes")
@Api(value = "/classes", description = "Add classes to waitlist, drop classes from waitlist")
public class WaitlistController {

	private Validator					validator;

	private IvoryService				ivoryService;

	private AcademicLevelService		academicLevelService;

	private RegDateService				regDateService;

	private ErrorMessageService			errorMessageService;

	private WaitlistQueueService		waitlistQueueService;

	private CheckIfClassWaitlistable	preAuthCheckService;

	private static final Logger			LOGTAG	= LoggerFactory.getLogger(WaitlistController.class);

	@Inject
	public WaitlistController(Validator validator, IvoryService ivoryService, RegDateService regDateService, AcademicLevelService academicLevelService, ErrorMessageService errorMessageService, WaitlistQueueService waitlistQueueService, CheckIfClassWaitlistable preAuthCheckService) {
		this.validator = validator;
		this.ivoryService = ivoryService;
		this.regDateService = regDateService;
		this.academicLevelService = academicLevelService;
		this.errorMessageService = errorMessageService;
		this.waitlistQueueService = waitlistQueueService;
		this.preAuthCheckService = preAuthCheckService;
	}
@SuppressWarnings("boxing")
	@POST
	@Path("/{sectionNumber: [0-9][0-9]*}/{pid: (.+)?}")
	@Produces(MediaType.APPLICATION_JSON)
	@Consumes(MediaType.APPLICATION_JSON)
	@ApiOperation(value = "Add class to the waitlist", notes = "Adding the student on the waiting list for the requested class", response = WaitlistStatusVo.class)
	public Response classWaitlist(@ApiParam(value = "User ID / PID", required = true) @PathParam("pid") String pid, @ApiParam(value = "4 characters alphanumeric Term code selected by user", required = true) @QueryParam("termCode") @NotNull String termCode, @ApiParam(value = "7 digit number unique for every class", required = true) @PathParam("sectionNumber") Integer sectionNumber, @ApiParam(value = "Payload", required = true) JsonNode jsonNode) {
}

**Comment by webron** [comment] 2015-06-16 17:15
What doesn't work?

**Comment by hiteshgupta33** [comment] 2015-06-16 17:30
@webron the url says 404...

**Comment by webron** [comment] 2015-06-16 17:41
Which URL do you try to open?

**Comment by hiteshgupta33** [comment] 2015-06-16 17:55
@webron  I tried localhost:8080/ClassWaitlist/v1/api-docs/classes
localhost:8080/ClassWaitlist/api-docs/classes
localhost:8080/ClassWaitlist/api-docs/classes

None of these work. 

But when I hit localhost:8080/ClassWaitlist/v1/api-docs , I get swagger and API version

**Comment by webron** [comment] 2015-06-16 17:58
Try http://localhost:8080/ClassWaitlist/v1/swagger.json

**Comment by hiteshgupta33** [comment] 2015-06-16 19:53
@webron  Thanks for the help . 

With the above config, I am not even able to deploy it on Jboss. 

Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [Set] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set)]"}}

And I think it is because of CDI

**Comment by webron** [comment] 2015-06-17 08:53
You're contradicting yourself. One time you say you can't open specific URLs and the other that you can't even deploy the app. I just don't know how to help you.

**Comment by hiteshgupta33** [comment] 2015-06-17 16:14
@webron  I know I got you confused there, Actually I was trying different configs for resteasy swagger config. The one specified above in my question doesn't even let me deploy it on Jboss. 

As you will notice that I have a constructor of classes with Inject annotation on it and that is the same class acting as resource for me. and that's why I am facing the above mentioned deployment error.

**Comment by diegogusava** [comment] 2015-07-02 12:33
I have the same problem ... I got the exception:
[2015-07-02 09:32:21,953] Artifact qualirede-rest:war: java.lang.Exception: {"JBAS014671: Falha de serviços" => {"jboss.deployment.unit.\"qualirede-rest.war\".WeldStartService" => "org.jboss.msc.service.StartException in service jboss.deployment.unit.\"qualirede-rest.war\".WeldStartService: Failed to start service
    Caused by: org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [Set<Service>] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)]"}}

**Comment by mpodrazik** [comment] 2015-07-07 15:35
same problem. anyone figure this out?

**Comment by webron** [comment] 2015-07-07 15:38
Can't help here without clearer details. If anyone wants to try and provide those, that would be great.

**Comment by XSR71** [comment] 2015-07-07 17:02
It is my understanding that swagger-core 1.5 requires CDI 2.0. EAP 6.2 has CDI 1.1.

**Comment by hiteshgupta33** [comment] 2015-07-07 17:34
EAP 6.2 has CDI 1.0


That's the problem.

On Tue, Jul 7, 2015 at 10:02 AM, XSR71 <notifications@github.com> wrote:

> It is my understanding that swagger-core 1.5 requires CDI 2.0. EAP 6.2 has
> CDI 1.1.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1170#issuecomment-119269098>
> .
>



-- 
Hi








*Regards Hitesh Gupta*

**Comment by webron** [comment] 2015-07-07 17:54
Where do you see that swagger-core requires any version of CDI?

**Comment by hiteshgupta33** [comment] 2015-07-07 21:57
I read a number of posts.


And the error mentioned in the above comments suggest that the reason is
CDI 1.0 version. Swagger-core doesn't require CDI but we are using CDI in
general for the other application components.

On Tue, Jul 7, 2015 at 10:54 AM, Ron <notifications@github.com> wrote:

> Where do you see that swagger-core requires any version of CDI?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1170#issuecomment-119283180>
> .
>



-- 
Hi








*Regards Hitesh Gupta*

**Comment by diegogusava** [comment] 2015-07-07 23:07
Well, I got it working ... just remove guava from dependencies

<dependency>
            <groupId>com.wordnik</groupId>
            <artifactId>swagger-jaxrs_2.10</artifactId>
            <version>1.3.12</version>
            <exclusions>
                <exclusion>
                    <groupId>com.google.guava</groupId>
                    <artifactId>guava</artifactId>
                </exclusion>
            </exclusions>
        </dependency>

**Comment by hiteshgupta33** [comment] 2015-07-07 23:44
How are you configuring it.

Are you using application class or web.xml config?


On Tue, Jul 7, 2015 at 4:07 PM, Diego Armando Gusava <
notifications@github.com> wrote:

> Well, I got it working ... just remove guava from dependencies
>
>
> com.wordnik
> swagger-jaxrs_2.10
> 1.3.12
>
>
> com.google.guava
> guava
>
>
>  —
> Reply to this email directly or view it on GitHub
> <https://github.com/swagger-api/swagger-core/issues/1170#issuecomment-119370370>
> .
>



-- 
Hi








*Regards Hitesh Gupta*

**Comment by diegogusava** [comment] 2015-07-07 23:50
I am using class config.

```java
@ApplicationPath("/rest")
public class AppConfiguration extends Application {

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<>();
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiListingResource.class);
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiDeclarationProvider.class);
        resources.add(com.wordnik.swagger.jaxrs.listing.ApiListingResourceJSON.class);
        resources.add(com.wordnik.swagger.jaxrs.listing.ResourceListingProvider.class);
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically populated with
     * all resources defined in the project.
     * If required, comment out calling this method in getClasses().
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(PrestadorEndpointImpl.class);
    }
}

```

and

```java
@WebServlet(name = "SwaggerJaxrsConfig", loadOnStartup = 1)
public class SwaggerJaxrsConfig extends HttpServlet {

    @Override
    public void init(ServletConfig servletConfig) {
        try {
            super.init(servletConfig);
            SwaggerConfig swaggerConfig = new SwaggerConfig();
            ConfigFactory.setConfig(swaggerConfig);
            swaggerConfig.setBasePath("http://localhost:8080/qualirede/rest");
            swaggerConfig.setApiVersion("1.0.0");
            ScannerFactory.setScanner(new DefaultJaxrsScanner());
            ClassReaders.setReader(new DefaultJaxrsApiReader());
        } catch (ServletException e) {
            System.out.println(e.getMessage());
        }
    }

}

```

**Comment by webron** [comment] 2015-07-13 16:52
I'm afraid I have to close this issue as there are no clear details. I'd be happy to reopen if anyone chooses to clarify.

**Closed by webron** 2015-07-13 16:52 UTC
Labels: Support

**Comment by lemoncolly** [comment] 2015-07-29 18:59
Hi all,

We are using CDI 1.0 on Liberty Profile.
I was able to get by the issue by upgrading the version of Google Guava.
Add this to your Maven dependencies:

<dependency>
		  <groupId>com.google.guava</groupId>
		  <artifactId>guava</artifactId>
		  <version>16.0</version>
		</dependency>

**Comment by webron** [comment] 2015-07-30 00:27
FWIW, the next release of swagger-core will upgrade the Guava dependency to 18.0.

**Comment by Rorkal** [comment] 2015-11-06 13:49
Hi ! 
I got the error WELD-001408 trying to deploy on a glassfish3.1.2 server:
```
[#|2015-11-06T14:32:13.348+0100|SEVERE|oracle-glassfish3.1.2|javax.enterprise.system.tools.admin.org.glassfish.deployment.admin|_ThreadID=67;_ThreadName=admin-thread-pool-4848(3);|Exception while loading the app : WELD-001408 Unsatisfied dependencies for type [Set<Service>] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)]
org.jboss.weld.exceptions.DeploymentException: WELD-001408 Unsatisfied dependencies for type [Set<Service>] with qualifiers [@Default] at injection point [[parameter 1] of [constructor] @Inject com.google.common.util.concurrent.ServiceManager(Set<Service>)]
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:311)
        at org.jboss.weld.bootstrap.Validator.validateInjectionPoint(Validator.java:280)
        at org.jboss.weld.bootstrap.Validator.validateBean(Validator.java:143)
        at org.jboss.weld.bootstrap.Validator.validateRIBean(Validator.java:163)
        at org.jboss.weld.bootstrap.Validator.validateBeans(Validator.java:382)
        at org.jboss.weld.bootstrap.Validator.validateDeployment(Validator.java:367)
        at org.jboss.weld.bootstrap.WeldBootstrap.validateBeans(WeldBootstrap.java:379)
        at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:199)
        at org.glassfish.kernel.event.EventsImpl.send(EventsImpl.java:128)
        at org.glassfish.internal.data.ApplicationInfo.start(ApplicationInfo.java:313)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:461)
        at com.sun.enterprise.v3.server.ApplicationLifecycle.deploy(ApplicationLifecycle.java:240)
        at org.glassfish.deployment.admin.DeployCommand.execute(DeployCommand.java:389)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$1.execute(CommandRunnerImpl.java:348)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:363)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.doCommand(CommandRunnerImpl.java:1085)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl.access$1200(CommandRunnerImpl.java:95)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1291)
        at com.sun.enterprise.v3.admin.CommandRunnerImpl$ExecutionContext.execute(CommandRunnerImpl.java:1259)
        at com.sun.enterprise.v3.admin.AdminAdapter.doCommand(AdminAdapter.java:461)
        at com.sun.enterprise.v3.admin.AdminAdapter.service(AdminAdapter.java:212)
        at com.sun.grizzly.tcp.http11.GrizzlyAdapter.service(GrizzlyAdapter.java:179)
        at com.sun.enterprise.v3.server.HK2Dispatcher.dispath(HK2Dispatcher.java:117)
        at com.sun.enterprise.v3.services.impl.ContainerMapper$Hk2DispatcherCallable.call(ContainerMapper.java:348)
        at com.sun.enterprise.v3.services.impl.ContainerMapper.service(ContainerMapper.java:189)
        at com.sun.grizzly.http.ProcessorTask.invokeAdapter(ProcessorTask.java:850)
        at com.sun.grizzly.http.ProcessorTask.doProcess(ProcessorTask.java:747)
        at com.sun.grizzly.http.ProcessorTask.process(ProcessorTask.java:1036)
        at com.sun.grizzly.http.DefaultProtocolFilter.execute(DefaultProtocolFilter.java:231)
        at com.sun.grizzly.DefaultProtocolChain.executeProtocolFilter(DefaultProtocolChain.java:137)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:104)
        at com.sun.grizzly.DefaultProtocolChain.execute(DefaultProtocolChain.java:90)
        at com.sun.grizzly.http.HttpProtocolChain.execute(HttpProtocolChain.java:79)
        at com.sun.grizzly.ProtocolChainContextTask.doCall(ProtocolChainContextTask.java:54)
        at com.sun.grizzly.SelectionKeyContextTask.call(SelectionKeyContextTask.java:59)
        at com.sun.grizzly.ContextTask.run(ContextTask.java:71)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.doWork(AbstractThreadPool.java:532)
        at com.sun.grizzly.util.AbstractThreadPool$Worker.run(AbstractThreadPool.java:513)
        at java.lang.Thread.run(Thread.java:745)
|#]

```
I could resolve the problem switching from version 1.5.0 to version 1.5.4 of swagger-jersey-jaxrs.

**Comment by fehguy** [comment] 2015-11-09 04:00
OK so you're all set by updating the dependency?

**Comment by Rorkal** [comment] 2015-11-09 12:22
With the update, the server does not crash when starting.
I still have issues with exposing my swagger.json file but I don't think it's related, a problem with my configuration of web.xml maybe. I'll let you know if  I got problems with version 1.5.4. :)

**Comment by kaushalsmile08** [comment] 2018-05-07 04:51
I am using servlet web.xml config. I tried using resteasy and jersery.
Web.xml
 <context-param>
        <param-name>resteasy.scan</param-name>
        <param-value>true</param-value>
    </context-param>
<servlet>
        <servlet-name>DefaultJaxrsConfig</servlet-name>
        <servlet-class>io.swagger.jaxrs.config.DefaultJaxrsConfig</servlet-class>
        <init-param>
            <param-name>api.version</param-name>
            <param-value>1.0.0</param-value>
       </init-param>
        <init-param>
            <param-name>swagger.api.basepath</param-name>
            <param-value>http://localhost:8080/ClassWaitlist</param-value>
        </init-param>
        <load-on-startup>2</load-on-startup>
    </servlet>

Pom.xml
<dependency>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-jaxrs</artifactId>
        <version>1.5.8</version>
      </dependency
<dependency>
        <groupId>io.swagger</groupId>
        <artifactId>swagger-jersey2-jaxrs</artifactId>
        <version>1.5.4</version>
      </dependency>

And added @API annotation on some java class method. 
Please help to solve it

**Comment by kaushalsmile08** [comment] 2018-05-07 04:56
<context-param>
        <param-name>resteasy.resources</param-name>
        <param-value>io.swagger.jaxrs.listing.ApiListingResource,
             io.swagger.jaxrs.listing.SwaggerSerializers,
            com.walmart.services.api,
            com.walmart.wrapper.services.promise
        </param-value>
    </context-param>


    <context-param>
        <param-name>resteasy.providers</param-name>
        <param-value>
            io.swagger.jaxrs.json.JacksonJsonProvider,
            io.swagger.jaxrs.listing.ApiDeclarationProvider,
            io.swagger.jaxrs.listing.ResourceListingProvider
        </param-value>
    </context-param>
    <context-param>
        <param-name>resteasy.scan</param-name>
        <param-value>true</param-value>
    </context-param>

Also it is showing no class def found for io.swagger.jaxrs.config.DefaultJaxrsConfig
