### ISSUE TITLE
Default value for Parameter annotation

### ISSUE THREAD

**Issue by eduhAgostinho** [swagger-api/swagger-core#4174] opened 2022-05-05 14:08 UTC
I'm trying to set a default value for one of my query params, but the Parameter annotation doesn't have defaultValue. I tried using the prop schema and pass the value but it doesn't work. Is it a bug or am I doing something wrong? This is the example of what I'm trying to do: 
When I was using Swagger version 2, It was working with ApiImplicitParams annotation.

````
@GetMapping(path = "/user", produces = JSON_FORMAT)
    public ResponseEntity<PagedListDto<List<UserOutputDto>>> getUsers(
            @Parameter(description = DEFAULT_PAGE_DESCRIPTION, schema = @Schema(defaultValue = DEFAULT_PAGE))
            @RequestParam(defaultValue = DEFAULT_PAGE) Integer page,
            @Parameter(description = DEFAULT_LIMIT_DESCRIPTION, schema = @Schema(defaultValue = DEFAULT_LIMIT))
            @RequestParam(defaultValue = DEFAULT_LIMIT) Integer limit) {
       ...
    }

**Comment by thattolleyguy** [comment] 2022-09-24 20:49
+1, This seems like a weird oversight

**Comment by glau2** [comment] 2023-03-22 02:39
+1

**Comment by ThomasAndreSix** [comment] 2023-07-25 15:27
+1

**Comment by scintilla932** [comment] 2023-09-25 05:16
+1

**Comment by nttoan26** [comment] 2024-04-19 04:38
++1

**Comment by micryc** [comment] 2024-04-26 08:56
@eduhAgostinho This issue seems to be not reproducible even in springdoc env (which is outside of our scope anyway), closing this ticket, if you still have issues please reopen and provide a reproducible test project.

**Closed by micryc** 2024-04-26 08:56 UTC
